#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 58
#define LARGE_STATE_COUNT 27
#define SYMBOL_COUNT 24
#define ALIAS_COUNT 0
#define TOKEN_COUNT 11
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define PRODUCTION_ID_COUNT 1

enum {
  sym__base_expression = 1,
  anon_sym_LPAREN = 2,
  anon_sym_RPAREN = 3,
  anon_sym_LBRACE = 4,
  anon_sym_RBRACE = 5,
  anon_sym_LBRACK = 6,
  anon_sym_RBRACK = 7,
  anon_sym_DQUOTE = 8,
  anon_sym_SQUOTE = 9,
  anon_sym_BQUOTE = 10,
  sym_source_file = 11,
  sym__expression = 12,
  sym_expressions = 13,
  sym__bracket_expression = 14,
  sym__quote_expression = 15,
  sym_paren_expression = 16,
  sym_brace_expression = 17,
  sym_bracket_expression = 18,
  sym_double_quote_expression = 19,
  sym_single_quote_expression = 20,
  sym_backtick_quote_expression = 21,
  aux_sym_source_file_repeat1 = 22,
  aux_sym_expressions_repeat1 = 23,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__base_expression] = "_base_expression",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_BQUOTE] = "`",
  [sym_source_file] = "source_file",
  [sym__expression] = "_expression",
  [sym_expressions] = "expressions",
  [sym__bracket_expression] = "_bracket_expression",
  [sym__quote_expression] = "_quote_expression",
  [sym_paren_expression] = "paren_expression",
  [sym_brace_expression] = "brace_expression",
  [sym_bracket_expression] = "bracket_expression",
  [sym_double_quote_expression] = "double_quote_expression",
  [sym_single_quote_expression] = "single_quote_expression",
  [sym_backtick_quote_expression] = "backtick_quote_expression",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_expressions_repeat1] = "expressions_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__base_expression] = sym__base_expression,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [sym_source_file] = sym_source_file,
  [sym__expression] = sym__expression,
  [sym_expressions] = sym_expressions,
  [sym__bracket_expression] = sym__bracket_expression,
  [sym__quote_expression] = sym__quote_expression,
  [sym_paren_expression] = sym_paren_expression,
  [sym_brace_expression] = sym_brace_expression,
  [sym_bracket_expression] = sym_bracket_expression,
  [sym_double_quote_expression] = sym_double_quote_expression,
  [sym_single_quote_expression] = sym_single_quote_expression,
  [sym_backtick_quote_expression] = sym_backtick_quote_expression,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_expressions_repeat1] = aux_sym_expressions_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__base_expression] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_expressions] = {
    .visible = true,
    .named = true,
  },
  [sym__bracket_expression] = {
    .visible = false,
    .named = true,
  },
  [sym__quote_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_paren_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_brace_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_bracket_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_double_quote_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_single_quote_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_backtick_quote_expression] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expressions_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 10,
  [12] = 2,
  [13] = 3,
  [14] = 8,
  [15] = 4,
  [16] = 9,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 19,
  [21] = 18,
  [22] = 22,
  [23] = 22,
  [24] = 5,
  [25] = 5,
  [26] = 5,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 34,
  [37] = 35,
  [38] = 32,
  [39] = 27,
  [40] = 28,
  [41] = 29,
  [42] = 30,
  [43] = 31,
  [44] = 33,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 50,
  [53] = 48,
  [54] = 45,
  [55] = 46,
  [56] = 47,
  [57] = 51,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(2);
      if (lookahead == '"') ADVANCE(11);
      if (lookahead == '\'') ADVANCE(12);
      if (lookahead == '(') ADVANCE(5);
      if (lookahead == ')') ADVANCE(6);
      if (lookahead == '[') ADVANCE(9);
      if (lookahead == ']') ADVANCE(10);
      if (lookahead == '`') ADVANCE(13);
      if (lookahead == '{') ADVANCE(7);
      if (lookahead == '}') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(3);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(11);
      if (lookahead == '\'') ADVANCE(12);
      if (lookahead == ')') ADVANCE(6);
      if (lookahead == ']') ADVANCE(10);
      if (lookahead == '`') ADVANCE(13);
      if (lookahead == '}') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      END_STATE();
    case 2:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(sym__base_expression);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(3);
      if (lookahead != 0 &&
          lookahead != '"' &&
          (lookahead < '\'' || ')' < lookahead) &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '`' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(4);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(sym__base_expression);
      if (lookahead != 0 &&
          lookahead != '"' &&
          (lookahead < '\'' || ')' < lookahead) &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '`' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(4);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 1},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__base_expression] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(49),
    [sym__expression] = STATE(7),
    [sym__bracket_expression] = STATE(7),
    [sym__quote_expression] = STATE(7),
    [sym_paren_expression] = STATE(7),
    [sym_brace_expression] = STATE(7),
    [sym_bracket_expression] = STATE(7),
    [sym_double_quote_expression] = STATE(7),
    [sym_single_quote_expression] = STATE(7),
    [sym_backtick_quote_expression] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym__base_expression] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
  },
  [2] = {
    [sym_expressions] = STATE(55),
    [sym__bracket_expression] = STATE(25),
    [sym__quote_expression] = STATE(25),
    [sym_paren_expression] = STATE(25),
    [sym_brace_expression] = STATE(25),
    [sym_bracket_expression] = STATE(25),
    [sym_double_quote_expression] = STATE(25),
    [sym_single_quote_expression] = STATE(25),
    [sym_backtick_quote_expression] = STATE(25),
    [aux_sym_expressions_repeat1] = STATE(25),
    [sym__base_expression] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_RPAREN] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(21),
    [anon_sym_RBRACE] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_RBRACK] = ACTIONS(21),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [anon_sym_SQUOTE] = ACTIONS(21),
    [anon_sym_BQUOTE] = ACTIONS(21),
  },
  [3] = {
    [sym_expressions] = STATE(56),
    [sym__bracket_expression] = STATE(26),
    [sym__quote_expression] = STATE(26),
    [sym_paren_expression] = STATE(26),
    [sym_brace_expression] = STATE(26),
    [sym_bracket_expression] = STATE(26),
    [sym_double_quote_expression] = STATE(26),
    [sym_single_quote_expression] = STATE(26),
    [sym_backtick_quote_expression] = STATE(26),
    [aux_sym_expressions_repeat1] = STATE(26),
    [sym__base_expression] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(25),
    [anon_sym_RPAREN] = ACTIONS(25),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_RBRACE] = ACTIONS(25),
    [anon_sym_LBRACK] = ACTIONS(25),
    [anon_sym_RBRACK] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(25),
    [anon_sym_SQUOTE] = ACTIONS(25),
    [anon_sym_BQUOTE] = ACTIONS(25),
  },
  [4] = {
    [sym_expressions] = STATE(57),
    [sym__bracket_expression] = STATE(24),
    [sym__quote_expression] = STATE(24),
    [sym_paren_expression] = STATE(24),
    [sym_brace_expression] = STATE(24),
    [sym_bracket_expression] = STATE(24),
    [sym_double_quote_expression] = STATE(24),
    [sym_single_quote_expression] = STATE(24),
    [sym_backtick_quote_expression] = STATE(24),
    [aux_sym_expressions_repeat1] = STATE(24),
    [sym__base_expression] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_RPAREN] = ACTIONS(29),
    [anon_sym_LBRACE] = ACTIONS(29),
    [anon_sym_RBRACE] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(29),
    [anon_sym_RBRACK] = ACTIONS(29),
    [anon_sym_DQUOTE] = ACTIONS(29),
    [anon_sym_SQUOTE] = ACTIONS(29),
    [anon_sym_BQUOTE] = ACTIONS(29),
  },
  [5] = {
    [sym__bracket_expression] = STATE(6),
    [sym__quote_expression] = STATE(6),
    [sym_paren_expression] = STATE(6),
    [sym_brace_expression] = STATE(6),
    [sym_bracket_expression] = STATE(6),
    [sym_double_quote_expression] = STATE(6),
    [sym_single_quote_expression] = STATE(6),
    [sym_backtick_quote_expression] = STATE(6),
    [aux_sym_expressions_repeat1] = STATE(6),
    [sym__base_expression] = ACTIONS(31),
    [anon_sym_LPAREN] = ACTIONS(33),
    [anon_sym_RPAREN] = ACTIONS(35),
    [anon_sym_LBRACE] = ACTIONS(37),
    [anon_sym_RBRACE] = ACTIONS(35),
    [anon_sym_LBRACK] = ACTIONS(39),
    [anon_sym_RBRACK] = ACTIONS(35),
    [anon_sym_DQUOTE] = ACTIONS(41),
    [anon_sym_SQUOTE] = ACTIONS(43),
    [anon_sym_BQUOTE] = ACTIONS(45),
  },
  [6] = {
    [sym__bracket_expression] = STATE(6),
    [sym__quote_expression] = STATE(6),
    [sym_paren_expression] = STATE(6),
    [sym_brace_expression] = STATE(6),
    [sym_bracket_expression] = STATE(6),
    [sym_double_quote_expression] = STATE(6),
    [sym_single_quote_expression] = STATE(6),
    [sym_backtick_quote_expression] = STATE(6),
    [aux_sym_expressions_repeat1] = STATE(6),
    [sym__base_expression] = ACTIONS(47),
    [anon_sym_LPAREN] = ACTIONS(50),
    [anon_sym_RPAREN] = ACTIONS(53),
    [anon_sym_LBRACE] = ACTIONS(55),
    [anon_sym_RBRACE] = ACTIONS(53),
    [anon_sym_LBRACK] = ACTIONS(58),
    [anon_sym_RBRACK] = ACTIONS(53),
    [anon_sym_DQUOTE] = ACTIONS(61),
    [anon_sym_SQUOTE] = ACTIONS(64),
    [anon_sym_BQUOTE] = ACTIONS(67),
  },
  [7] = {
    [sym__expression] = STATE(17),
    [sym__bracket_expression] = STATE(17),
    [sym__quote_expression] = STATE(17),
    [sym_paren_expression] = STATE(17),
    [sym_brace_expression] = STATE(17),
    [sym_bracket_expression] = STATE(17),
    [sym_double_quote_expression] = STATE(17),
    [sym_single_quote_expression] = STATE(17),
    [sym_backtick_quote_expression] = STATE(17),
    [aux_sym_source_file_repeat1] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(70),
    [sym__base_expression] = ACTIONS(72),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
  },
  [8] = {
    [sym_expressions] = STATE(54),
    [sym__bracket_expression] = STATE(5),
    [sym__quote_expression] = STATE(5),
    [sym_paren_expression] = STATE(5),
    [sym_brace_expression] = STATE(5),
    [sym_bracket_expression] = STATE(5),
    [sym_double_quote_expression] = STATE(5),
    [sym_single_quote_expression] = STATE(5),
    [sym_backtick_quote_expression] = STATE(5),
    [aux_sym_expressions_repeat1] = STATE(5),
    [sym__base_expression] = ACTIONS(74),
    [anon_sym_LPAREN] = ACTIONS(33),
    [anon_sym_LBRACE] = ACTIONS(37),
    [anon_sym_LBRACK] = ACTIONS(39),
    [anon_sym_RBRACK] = ACTIONS(76),
    [anon_sym_DQUOTE] = ACTIONS(41),
    [anon_sym_SQUOTE] = ACTIONS(43),
    [anon_sym_BQUOTE] = ACTIONS(45),
  },
  [9] = {
    [sym_expressions] = STATE(53),
    [sym__bracket_expression] = STATE(5),
    [sym__quote_expression] = STATE(5),
    [sym_paren_expression] = STATE(5),
    [sym_brace_expression] = STATE(5),
    [sym_bracket_expression] = STATE(5),
    [sym_double_quote_expression] = STATE(5),
    [sym_single_quote_expression] = STATE(5),
    [sym_backtick_quote_expression] = STATE(5),
    [aux_sym_expressions_repeat1] = STATE(5),
    [sym__base_expression] = ACTIONS(74),
    [anon_sym_LPAREN] = ACTIONS(33),
    [anon_sym_LBRACE] = ACTIONS(37),
    [anon_sym_RBRACE] = ACTIONS(78),
    [anon_sym_LBRACK] = ACTIONS(39),
    [anon_sym_DQUOTE] = ACTIONS(41),
    [anon_sym_SQUOTE] = ACTIONS(43),
    [anon_sym_BQUOTE] = ACTIONS(45),
  },
  [10] = {
    [sym_expressions] = STATE(50),
    [sym__bracket_expression] = STATE(5),
    [sym__quote_expression] = STATE(5),
    [sym_paren_expression] = STATE(5),
    [sym_brace_expression] = STATE(5),
    [sym_bracket_expression] = STATE(5),
    [sym_double_quote_expression] = STATE(5),
    [sym_single_quote_expression] = STATE(5),
    [sym_backtick_quote_expression] = STATE(5),
    [aux_sym_expressions_repeat1] = STATE(5),
    [sym__base_expression] = ACTIONS(74),
    [anon_sym_LPAREN] = ACTIONS(33),
    [anon_sym_RPAREN] = ACTIONS(80),
    [anon_sym_LBRACE] = ACTIONS(37),
    [anon_sym_LBRACK] = ACTIONS(39),
    [anon_sym_DQUOTE] = ACTIONS(41),
    [anon_sym_SQUOTE] = ACTIONS(43),
    [anon_sym_BQUOTE] = ACTIONS(45),
  },
  [11] = {
    [sym_expressions] = STATE(52),
    [sym__bracket_expression] = STATE(5),
    [sym__quote_expression] = STATE(5),
    [sym_paren_expression] = STATE(5),
    [sym_brace_expression] = STATE(5),
    [sym_bracket_expression] = STATE(5),
    [sym_double_quote_expression] = STATE(5),
    [sym_single_quote_expression] = STATE(5),
    [sym_backtick_quote_expression] = STATE(5),
    [aux_sym_expressions_repeat1] = STATE(5),
    [sym__base_expression] = ACTIONS(74),
    [anon_sym_LPAREN] = ACTIONS(33),
    [anon_sym_RPAREN] = ACTIONS(82),
    [anon_sym_LBRACE] = ACTIONS(37),
    [anon_sym_LBRACK] = ACTIONS(39),
    [anon_sym_DQUOTE] = ACTIONS(41),
    [anon_sym_SQUOTE] = ACTIONS(43),
    [anon_sym_BQUOTE] = ACTIONS(45),
  },
  [12] = {
    [sym_expressions] = STATE(55),
    [sym__bracket_expression] = STATE(25),
    [sym__quote_expression] = STATE(25),
    [sym_paren_expression] = STATE(25),
    [sym_brace_expression] = STATE(25),
    [sym_bracket_expression] = STATE(25),
    [sym_double_quote_expression] = STATE(25),
    [sym_single_quote_expression] = STATE(25),
    [sym_backtick_quote_expression] = STATE(25),
    [aux_sym_expressions_repeat1] = STATE(25),
    [ts_builtin_sym_end] = ACTIONS(19),
    [sym__base_expression] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(21),
    [anon_sym_LBRACK] = ACTIONS(21),
    [anon_sym_DQUOTE] = ACTIONS(21),
    [anon_sym_SQUOTE] = ACTIONS(21),
    [anon_sym_BQUOTE] = ACTIONS(21),
  },
  [13] = {
    [sym_expressions] = STATE(56),
    [sym__bracket_expression] = STATE(26),
    [sym__quote_expression] = STATE(26),
    [sym_paren_expression] = STATE(26),
    [sym_brace_expression] = STATE(26),
    [sym_bracket_expression] = STATE(26),
    [sym_double_quote_expression] = STATE(26),
    [sym_single_quote_expression] = STATE(26),
    [sym_backtick_quote_expression] = STATE(26),
    [aux_sym_expressions_repeat1] = STATE(26),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym__base_expression] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(25),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_LBRACK] = ACTIONS(25),
    [anon_sym_DQUOTE] = ACTIONS(25),
    [anon_sym_SQUOTE] = ACTIONS(25),
    [anon_sym_BQUOTE] = ACTIONS(25),
  },
  [14] = {
    [sym_expressions] = STATE(45),
    [sym__bracket_expression] = STATE(5),
    [sym__quote_expression] = STATE(5),
    [sym_paren_expression] = STATE(5),
    [sym_brace_expression] = STATE(5),
    [sym_bracket_expression] = STATE(5),
    [sym_double_quote_expression] = STATE(5),
    [sym_single_quote_expression] = STATE(5),
    [sym_backtick_quote_expression] = STATE(5),
    [aux_sym_expressions_repeat1] = STATE(5),
    [sym__base_expression] = ACTIONS(74),
    [anon_sym_LPAREN] = ACTIONS(33),
    [anon_sym_LBRACE] = ACTIONS(37),
    [anon_sym_LBRACK] = ACTIONS(39),
    [anon_sym_RBRACK] = ACTIONS(84),
    [anon_sym_DQUOTE] = ACTIONS(41),
    [anon_sym_SQUOTE] = ACTIONS(43),
    [anon_sym_BQUOTE] = ACTIONS(45),
  },
  [15] = {
    [sym_expressions] = STATE(57),
    [sym__bracket_expression] = STATE(24),
    [sym__quote_expression] = STATE(24),
    [sym_paren_expression] = STATE(24),
    [sym_brace_expression] = STATE(24),
    [sym_bracket_expression] = STATE(24),
    [sym_double_quote_expression] = STATE(24),
    [sym_single_quote_expression] = STATE(24),
    [sym_backtick_quote_expression] = STATE(24),
    [aux_sym_expressions_repeat1] = STATE(24),
    [ts_builtin_sym_end] = ACTIONS(27),
    [sym__base_expression] = ACTIONS(27),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_LBRACE] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(29),
    [anon_sym_DQUOTE] = ACTIONS(29),
    [anon_sym_SQUOTE] = ACTIONS(29),
    [anon_sym_BQUOTE] = ACTIONS(29),
  },
  [16] = {
    [sym_expressions] = STATE(48),
    [sym__bracket_expression] = STATE(5),
    [sym__quote_expression] = STATE(5),
    [sym_paren_expression] = STATE(5),
    [sym_brace_expression] = STATE(5),
    [sym_bracket_expression] = STATE(5),
    [sym_double_quote_expression] = STATE(5),
    [sym_single_quote_expression] = STATE(5),
    [sym_backtick_quote_expression] = STATE(5),
    [aux_sym_expressions_repeat1] = STATE(5),
    [sym__base_expression] = ACTIONS(74),
    [anon_sym_LPAREN] = ACTIONS(33),
    [anon_sym_LBRACE] = ACTIONS(37),
    [anon_sym_RBRACE] = ACTIONS(86),
    [anon_sym_LBRACK] = ACTIONS(39),
    [anon_sym_DQUOTE] = ACTIONS(41),
    [anon_sym_SQUOTE] = ACTIONS(43),
    [anon_sym_BQUOTE] = ACTIONS(45),
  },
  [17] = {
    [sym__expression] = STATE(17),
    [sym__bracket_expression] = STATE(17),
    [sym__quote_expression] = STATE(17),
    [sym_paren_expression] = STATE(17),
    [sym_brace_expression] = STATE(17),
    [sym_bracket_expression] = STATE(17),
    [sym_double_quote_expression] = STATE(17),
    [sym_single_quote_expression] = STATE(17),
    [sym_backtick_quote_expression] = STATE(17),
    [aux_sym_source_file_repeat1] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(88),
    [sym__base_expression] = ACTIONS(90),
    [anon_sym_LPAREN] = ACTIONS(93),
    [anon_sym_LBRACE] = ACTIONS(96),
    [anon_sym_LBRACK] = ACTIONS(99),
    [anon_sym_DQUOTE] = ACTIONS(102),
    [anon_sym_SQUOTE] = ACTIONS(105),
    [anon_sym_BQUOTE] = ACTIONS(108),
  },
  [18] = {
    [sym_expressions] = STATE(47),
    [sym__bracket_expression] = STATE(26),
    [sym__quote_expression] = STATE(26),
    [sym_paren_expression] = STATE(26),
    [sym_brace_expression] = STATE(26),
    [sym_bracket_expression] = STATE(26),
    [sym_double_quote_expression] = STATE(26),
    [sym_single_quote_expression] = STATE(26),
    [sym_backtick_quote_expression] = STATE(26),
    [aux_sym_expressions_repeat1] = STATE(26),
    [sym__base_expression] = ACTIONS(111),
    [anon_sym_LPAREN] = ACTIONS(33),
    [anon_sym_LBRACE] = ACTIONS(37),
    [anon_sym_LBRACK] = ACTIONS(39),
    [anon_sym_DQUOTE] = ACTIONS(41),
    [anon_sym_SQUOTE] = ACTIONS(113),
    [anon_sym_BQUOTE] = ACTIONS(45),
  },
  [19] = {
    [sym_expressions] = STATE(51),
    [sym__bracket_expression] = STATE(24),
    [sym__quote_expression] = STATE(24),
    [sym_paren_expression] = STATE(24),
    [sym_brace_expression] = STATE(24),
    [sym_bracket_expression] = STATE(24),
    [sym_double_quote_expression] = STATE(24),
    [sym_single_quote_expression] = STATE(24),
    [sym_backtick_quote_expression] = STATE(24),
    [aux_sym_expressions_repeat1] = STATE(24),
    [sym__base_expression] = ACTIONS(115),
    [anon_sym_LPAREN] = ACTIONS(33),
    [anon_sym_LBRACE] = ACTIONS(37),
    [anon_sym_LBRACK] = ACTIONS(39),
    [anon_sym_DQUOTE] = ACTIONS(41),
    [anon_sym_SQUOTE] = ACTIONS(43),
    [anon_sym_BQUOTE] = ACTIONS(117),
  },
  [20] = {
    [sym_expressions] = STATE(57),
    [sym__bracket_expression] = STATE(24),
    [sym__quote_expression] = STATE(24),
    [sym_paren_expression] = STATE(24),
    [sym_brace_expression] = STATE(24),
    [sym_bracket_expression] = STATE(24),
    [sym_double_quote_expression] = STATE(24),
    [sym_single_quote_expression] = STATE(24),
    [sym_backtick_quote_expression] = STATE(24),
    [aux_sym_expressions_repeat1] = STATE(24),
    [sym__base_expression] = ACTIONS(115),
    [anon_sym_LPAREN] = ACTIONS(33),
    [anon_sym_LBRACE] = ACTIONS(37),
    [anon_sym_LBRACK] = ACTIONS(39),
    [anon_sym_DQUOTE] = ACTIONS(41),
    [anon_sym_SQUOTE] = ACTIONS(43),
    [anon_sym_BQUOTE] = ACTIONS(119),
  },
  [21] = {
    [sym_expressions] = STATE(56),
    [sym__bracket_expression] = STATE(26),
    [sym__quote_expression] = STATE(26),
    [sym_paren_expression] = STATE(26),
    [sym_brace_expression] = STATE(26),
    [sym_bracket_expression] = STATE(26),
    [sym_double_quote_expression] = STATE(26),
    [sym_single_quote_expression] = STATE(26),
    [sym_backtick_quote_expression] = STATE(26),
    [aux_sym_expressions_repeat1] = STATE(26),
    [sym__base_expression] = ACTIONS(111),
    [anon_sym_LPAREN] = ACTIONS(33),
    [anon_sym_LBRACE] = ACTIONS(37),
    [anon_sym_LBRACK] = ACTIONS(39),
    [anon_sym_DQUOTE] = ACTIONS(41),
    [anon_sym_SQUOTE] = ACTIONS(121),
    [anon_sym_BQUOTE] = ACTIONS(45),
  },
  [22] = {
    [sym_expressions] = STATE(55),
    [sym__bracket_expression] = STATE(25),
    [sym__quote_expression] = STATE(25),
    [sym_paren_expression] = STATE(25),
    [sym_brace_expression] = STATE(25),
    [sym_bracket_expression] = STATE(25),
    [sym_double_quote_expression] = STATE(25),
    [sym_single_quote_expression] = STATE(25),
    [sym_backtick_quote_expression] = STATE(25),
    [aux_sym_expressions_repeat1] = STATE(25),
    [sym__base_expression] = ACTIONS(123),
    [anon_sym_LPAREN] = ACTIONS(33),
    [anon_sym_LBRACE] = ACTIONS(37),
    [anon_sym_LBRACK] = ACTIONS(39),
    [anon_sym_DQUOTE] = ACTIONS(125),
    [anon_sym_SQUOTE] = ACTIONS(43),
    [anon_sym_BQUOTE] = ACTIONS(45),
  },
  [23] = {
    [sym_expressions] = STATE(46),
    [sym__bracket_expression] = STATE(25),
    [sym__quote_expression] = STATE(25),
    [sym_paren_expression] = STATE(25),
    [sym_brace_expression] = STATE(25),
    [sym_bracket_expression] = STATE(25),
    [sym_double_quote_expression] = STATE(25),
    [sym_single_quote_expression] = STATE(25),
    [sym_backtick_quote_expression] = STATE(25),
    [aux_sym_expressions_repeat1] = STATE(25),
    [sym__base_expression] = ACTIONS(123),
    [anon_sym_LPAREN] = ACTIONS(33),
    [anon_sym_LBRACE] = ACTIONS(37),
    [anon_sym_LBRACK] = ACTIONS(39),
    [anon_sym_DQUOTE] = ACTIONS(127),
    [anon_sym_SQUOTE] = ACTIONS(43),
    [anon_sym_BQUOTE] = ACTIONS(45),
  },
  [24] = {
    [sym__bracket_expression] = STATE(6),
    [sym__quote_expression] = STATE(6),
    [sym_paren_expression] = STATE(6),
    [sym_brace_expression] = STATE(6),
    [sym_bracket_expression] = STATE(6),
    [sym_double_quote_expression] = STATE(6),
    [sym_single_quote_expression] = STATE(6),
    [sym_backtick_quote_expression] = STATE(6),
    [aux_sym_expressions_repeat1] = STATE(6),
    [sym__base_expression] = ACTIONS(31),
    [anon_sym_LPAREN] = ACTIONS(33),
    [anon_sym_LBRACE] = ACTIONS(37),
    [anon_sym_LBRACK] = ACTIONS(39),
    [anon_sym_DQUOTE] = ACTIONS(41),
    [anon_sym_SQUOTE] = ACTIONS(43),
    [anon_sym_BQUOTE] = ACTIONS(35),
  },
  [25] = {
    [sym__bracket_expression] = STATE(6),
    [sym__quote_expression] = STATE(6),
    [sym_paren_expression] = STATE(6),
    [sym_brace_expression] = STATE(6),
    [sym_bracket_expression] = STATE(6),
    [sym_double_quote_expression] = STATE(6),
    [sym_single_quote_expression] = STATE(6),
    [sym_backtick_quote_expression] = STATE(6),
    [aux_sym_expressions_repeat1] = STATE(6),
    [sym__base_expression] = ACTIONS(31),
    [anon_sym_LPAREN] = ACTIONS(33),
    [anon_sym_LBRACE] = ACTIONS(37),
    [anon_sym_LBRACK] = ACTIONS(39),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [anon_sym_SQUOTE] = ACTIONS(43),
    [anon_sym_BQUOTE] = ACTIONS(45),
  },
  [26] = {
    [sym__bracket_expression] = STATE(6),
    [sym__quote_expression] = STATE(6),
    [sym_paren_expression] = STATE(6),
    [sym_brace_expression] = STATE(6),
    [sym_bracket_expression] = STATE(6),
    [sym_double_quote_expression] = STATE(6),
    [sym_single_quote_expression] = STATE(6),
    [sym_backtick_quote_expression] = STATE(6),
    [aux_sym_expressions_repeat1] = STATE(6),
    [sym__base_expression] = ACTIONS(31),
    [anon_sym_LPAREN] = ACTIONS(33),
    [anon_sym_LBRACE] = ACTIONS(37),
    [anon_sym_LBRACK] = ACTIONS(39),
    [anon_sym_DQUOTE] = ACTIONS(41),
    [anon_sym_SQUOTE] = ACTIONS(35),
    [anon_sym_BQUOTE] = ACTIONS(45),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(129), 1,
      sym__base_expression,
    ACTIONS(131), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [15] = 2,
    ACTIONS(133), 1,
      sym__base_expression,
    ACTIONS(135), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [30] = 2,
    ACTIONS(137), 1,
      sym__base_expression,
    ACTIONS(139), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [45] = 2,
    ACTIONS(141), 1,
      sym__base_expression,
    ACTIONS(143), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [60] = 2,
    ACTIONS(145), 1,
      sym__base_expression,
    ACTIONS(147), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [75] = 2,
    ACTIONS(149), 1,
      sym__base_expression,
    ACTIONS(151), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [90] = 2,
    ACTIONS(153), 1,
      sym__base_expression,
    ACTIONS(155), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [105] = 2,
    ACTIONS(157), 1,
      sym__base_expression,
    ACTIONS(159), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [120] = 2,
    ACTIONS(161), 1,
      sym__base_expression,
    ACTIONS(163), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [135] = 2,
    ACTIONS(157), 2,
      ts_builtin_sym_end,
      sym__base_expression,
    ACTIONS(159), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [148] = 2,
    ACTIONS(161), 2,
      ts_builtin_sym_end,
      sym__base_expression,
    ACTIONS(163), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [161] = 2,
    ACTIONS(149), 2,
      ts_builtin_sym_end,
      sym__base_expression,
    ACTIONS(151), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [174] = 2,
    ACTIONS(129), 2,
      ts_builtin_sym_end,
      sym__base_expression,
    ACTIONS(131), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [187] = 2,
    ACTIONS(133), 2,
      ts_builtin_sym_end,
      sym__base_expression,
    ACTIONS(135), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [200] = 2,
    ACTIONS(137), 2,
      ts_builtin_sym_end,
      sym__base_expression,
    ACTIONS(139), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [213] = 2,
    ACTIONS(141), 2,
      ts_builtin_sym_end,
      sym__base_expression,
    ACTIONS(143), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [226] = 2,
    ACTIONS(145), 2,
      ts_builtin_sym_end,
      sym__base_expression,
    ACTIONS(147), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [239] = 2,
    ACTIONS(153), 2,
      ts_builtin_sym_end,
      sym__base_expression,
    ACTIONS(155), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [252] = 1,
    ACTIONS(165), 1,
      anon_sym_RBRACK,
  [256] = 1,
    ACTIONS(167), 1,
      anon_sym_DQUOTE,
  [260] = 1,
    ACTIONS(169), 1,
      anon_sym_SQUOTE,
  [264] = 1,
    ACTIONS(171), 1,
      anon_sym_RBRACE,
  [268] = 1,
    ACTIONS(173), 1,
      ts_builtin_sym_end,
  [272] = 1,
    ACTIONS(175), 1,
      anon_sym_RPAREN,
  [276] = 1,
    ACTIONS(177), 1,
      anon_sym_BQUOTE,
  [280] = 1,
    ACTIONS(179), 1,
      anon_sym_RPAREN,
  [284] = 1,
    ACTIONS(181), 1,
      anon_sym_RBRACE,
  [288] = 1,
    ACTIONS(183), 1,
      anon_sym_RBRACK,
  [292] = 1,
    ACTIONS(185), 1,
      anon_sym_DQUOTE,
  [296] = 1,
    ACTIONS(187), 1,
      anon_sym_SQUOTE,
  [300] = 1,
    ACTIONS(189), 1,
      anon_sym_BQUOTE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(27)] = 0,
  [SMALL_STATE(28)] = 15,
  [SMALL_STATE(29)] = 30,
  [SMALL_STATE(30)] = 45,
  [SMALL_STATE(31)] = 60,
  [SMALL_STATE(32)] = 75,
  [SMALL_STATE(33)] = 90,
  [SMALL_STATE(34)] = 105,
  [SMALL_STATE(35)] = 120,
  [SMALL_STATE(36)] = 135,
  [SMALL_STATE(37)] = 148,
  [SMALL_STATE(38)] = 161,
  [SMALL_STATE(39)] = 174,
  [SMALL_STATE(40)] = 187,
  [SMALL_STATE(41)] = 200,
  [SMALL_STATE(42)] = 213,
  [SMALL_STATE(43)] = 226,
  [SMALL_STATE(44)] = 239,
  [SMALL_STATE(45)] = 252,
  [SMALL_STATE(46)] = 256,
  [SMALL_STATE(47)] = 260,
  [SMALL_STATE(48)] = 264,
  [SMALL_STATE(49)] = 268,
  [SMALL_STATE(50)] = 272,
  [SMALL_STATE(51)] = 276,
  [SMALL_STATE(52)] = 280,
  [SMALL_STATE(53)] = 284,
  [SMALL_STATE(54)] = 288,
  [SMALL_STATE(55)] = 292,
  [SMALL_STATE(56)] = 296,
  [SMALL_STATE(57)] = 300,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_double_quote_expression, 2),
  [21] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_double_quote_expression, 2),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_single_quote_expression, 2),
  [25] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_single_quote_expression, 2),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_backtick_quote_expression, 2),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_backtick_quote_expression, 2),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expressions, 1),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expressions_repeat1, 2), SHIFT_REPEAT(6),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expressions_repeat1, 2), SHIFT_REPEAT(11),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_expressions_repeat1, 2),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expressions_repeat1, 2), SHIFT_REPEAT(9),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expressions_repeat1, 2), SHIFT_REPEAT(8),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expressions_repeat1, 2), SHIFT_REPEAT(22),
  [64] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expressions_repeat1, 2), SHIFT_REPEAT(21),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expressions_repeat1, 2), SHIFT_REPEAT(20),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [78] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [80] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [82] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [84] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [86] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(17),
  [93] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(10),
  [96] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(16),
  [99] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(14),
  [102] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(23),
  [105] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(18),
  [108] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(19),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [113] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [127] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_single_quote_expression, 3),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_single_quote_expression, 3),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_double_quote_expression, 3),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_double_quote_expression, 3),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bracket_expression, 3),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bracket_expression, 3),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_brace_expression, 3),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_brace_expression, 3),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paren_expression, 3),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paren_expression, 3),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paren_expression, 2),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paren_expression, 2),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_brace_expression, 2),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_brace_expression, 2),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bracket_expression, 2),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bracket_expression, 2),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_backtick_quote_expression, 3),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_backtick_quote_expression, 3),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [173] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_yard(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
