#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 60
#define LARGE_STATE_COUNT 24
#define SYMBOL_COUNT 27
#define ALIAS_COUNT 0
#define TOKEN_COUNT 13
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define PRODUCTION_ID_COUNT 1

enum {
  sym__base_expression = 1,
  anon_sym_LPAREN = 2,
  anon_sym_RPAREN = 3,
  anon_sym_LBRACE = 4,
  anon_sym_RBRACE = 5,
  anon_sym_LBRACK = 6,
  anon_sym_RBRACK = 7,
  anon_sym_DQUOTE = 8,
  anon_sym_SQUOTE = 9,
  anon_sym_BQUOTE = 10,
  anon_sym_SLASH_STAR = 11,
  anon_sym_STAR_SLASH = 12,
  sym_source_file = 13,
  sym__expression = 14,
  sym_expressions = 15,
  sym__bracket_expression = 16,
  sym__quote_expression = 17,
  sym_paren_expression = 18,
  sym_brace_expression = 19,
  sym_bracket_expression = 20,
  sym_double_quote_expression = 21,
  sym_single_quote_expression = 22,
  sym_backtick_quote_expression = 23,
  aux_sym_source_file_repeat1 = 24,
  aux_sym_expressions_repeat1 = 25,
  aux_sym_expressions_repeat2 = 26,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__base_expression] = "_base_expression",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_SQUOTE] = "'",
  [anon_sym_BQUOTE] = "`",
  [anon_sym_SLASH_STAR] = "/*",
  [anon_sym_STAR_SLASH] = "*/",
  [sym_source_file] = "source_file",
  [sym__expression] = "_expression",
  [sym_expressions] = "expressions",
  [sym__bracket_expression] = "_bracket_expression",
  [sym__quote_expression] = "_quote_expression",
  [sym_paren_expression] = "paren_expression",
  [sym_brace_expression] = "brace_expression",
  [sym_bracket_expression] = "bracket_expression",
  [sym_double_quote_expression] = "double_quote_expression",
  [sym_single_quote_expression] = "single_quote_expression",
  [sym_backtick_quote_expression] = "backtick_quote_expression",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_expressions_repeat1] = "expressions_repeat1",
  [aux_sym_expressions_repeat2] = "expressions_repeat2",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__base_expression] = sym__base_expression,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [anon_sym_BQUOTE] = anon_sym_BQUOTE,
  [anon_sym_SLASH_STAR] = anon_sym_SLASH_STAR,
  [anon_sym_STAR_SLASH] = anon_sym_STAR_SLASH,
  [sym_source_file] = sym_source_file,
  [sym__expression] = sym__expression,
  [sym_expressions] = sym_expressions,
  [sym__bracket_expression] = sym__bracket_expression,
  [sym__quote_expression] = sym__quote_expression,
  [sym_paren_expression] = sym_paren_expression,
  [sym_brace_expression] = sym_brace_expression,
  [sym_bracket_expression] = sym_bracket_expression,
  [sym_double_quote_expression] = sym_double_quote_expression,
  [sym_single_quote_expression] = sym_single_quote_expression,
  [sym_backtick_quote_expression] = sym_backtick_quote_expression,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_expressions_repeat1] = aux_sym_expressions_repeat1,
  [aux_sym_expressions_repeat2] = aux_sym_expressions_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__base_expression] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_expressions] = {
    .visible = true,
    .named = true,
  },
  [sym__bracket_expression] = {
    .visible = false,
    .named = true,
  },
  [sym__quote_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_paren_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_brace_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_bracket_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_double_quote_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_single_quote_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_backtick_quote_expression] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expressions_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_expressions_repeat2] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 5,
  [9] = 4,
  [10] = 3,
  [11] = 2,
  [12] = 7,
  [13] = 6,
  [14] = 14,
  [15] = 15,
  [16] = 15,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 14,
  [21] = 17,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 29,
  [34] = 24,
  [35] = 35,
  [36] = 31,
  [37] = 26,
  [38] = 27,
  [39] = 28,
  [40] = 40,
  [41] = 30,
  [42] = 24,
  [43] = 24,
  [44] = 40,
  [45] = 35,
  [46] = 32,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 52,
  [55] = 50,
  [56] = 48,
  [57] = 47,
  [58] = 49,
  [59] = 51,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      if (lookahead == '"') ADVANCE(13);
      if (lookahead == '\'') ADVANCE(14);
      if (lookahead == '(') ADVANCE(7);
      if (lookahead == ')') ADVANCE(8);
      if (lookahead == '*') ADVANCE(2);
      if (lookahead == '/') ADVANCE(1);
      if (lookahead == '[') ADVANCE(11);
      if (lookahead == ']') ADVANCE(12);
      if (lookahead == '`') ADVANCE(15);
      if (lookahead == '{') ADVANCE(9);
      if (lookahead == '}') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == '*') ADVANCE(16);
      END_STATE();
    case 2:
      if (lookahead == '/') ADVANCE(17);
      END_STATE();
    case 3:
      if (eof) ADVANCE(4);
      if (lookahead == '"') ADVANCE(13);
      if (lookahead == '\'') ADVANCE(14);
      if (lookahead == '(') ADVANCE(7);
      if (lookahead == ')') ADVANCE(8);
      if (lookahead == '[') ADVANCE(11);
      if (lookahead == ']') ADVANCE(12);
      if (lookahead == '`') ADVANCE(15);
      if (lookahead == '{') ADVANCE(9);
      if (lookahead == '}') ADVANCE(10);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(5);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(sym__base_expression);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(5);
      if (lookahead != 0 &&
          lookahead != '"' &&
          (lookahead < '\'' || ')' < lookahead) &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '`' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(6);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym__base_expression);
      if (lookahead != 0 &&
          lookahead != '"' &&
          (lookahead < '\'' || ')' < lookahead) &&
          lookahead != '[' &&
          lookahead != ']' &&
          lookahead != '`' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(6);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_BQUOTE);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_STAR_SLASH);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 3},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 3},
  [17] = {.lex_state = 3},
  [18] = {.lex_state = 3},
  [19] = {.lex_state = 3},
  [20] = {.lex_state = 3},
  [21] = {.lex_state = 3},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 3},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 3},
  [29] = {.lex_state = 3},
  [30] = {.lex_state = 3},
  [31] = {.lex_state = 3},
  [32] = {.lex_state = 3},
  [33] = {.lex_state = 3},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 3},
  [37] = {.lex_state = 3},
  [38] = {.lex_state = 3},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 3},
  [41] = {.lex_state = 3},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_BQUOTE] = ACTIONS(1),
    [anon_sym_SLASH_STAR] = ACTIONS(1),
    [anon_sym_STAR_SLASH] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(53),
    [sym__expression] = STATE(18),
    [sym__bracket_expression] = STATE(18),
    [sym__quote_expression] = STATE(18),
    [sym_paren_expression] = STATE(18),
    [sym_brace_expression] = STATE(18),
    [sym_bracket_expression] = STATE(18),
    [sym_double_quote_expression] = STATE(18),
    [sym_single_quote_expression] = STATE(18),
    [sym_backtick_quote_expression] = STATE(18),
    [aux_sym_source_file_repeat1] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym__base_expression] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
  },
  [2] = {
    [sym_expressions] = STATE(57),
    [sym__bracket_expression] = STATE(22),
    [sym__quote_expression] = STATE(34),
    [sym_paren_expression] = STATE(22),
    [sym_brace_expression] = STATE(22),
    [sym_bracket_expression] = STATE(22),
    [sym_double_quote_expression] = STATE(34),
    [sym_single_quote_expression] = STATE(34),
    [sym_backtick_quote_expression] = STATE(34),
    [aux_sym_expressions_repeat1] = STATE(22),
    [aux_sym_expressions_repeat2] = STATE(34),
    [sym__base_expression] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_RPAREN] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_RBRACE] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_RBRACK] = ACTIONS(23),
    [anon_sym_DQUOTE] = ACTIONS(23),
    [anon_sym_SQUOTE] = ACTIONS(23),
    [anon_sym_BQUOTE] = ACTIONS(23),
  },
  [3] = {
    [sym_expressions] = STATE(58),
    [sym__bracket_expression] = STATE(22),
    [sym__quote_expression] = STATE(43),
    [sym_paren_expression] = STATE(22),
    [sym_brace_expression] = STATE(22),
    [sym_bracket_expression] = STATE(22),
    [sym_double_quote_expression] = STATE(43),
    [sym_single_quote_expression] = STATE(43),
    [sym_backtick_quote_expression] = STATE(43),
    [aux_sym_expressions_repeat1] = STATE(22),
    [aux_sym_expressions_repeat2] = STATE(43),
    [sym__base_expression] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_RPAREN] = ACTIONS(29),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_RBRACE] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_RBRACK] = ACTIONS(29),
    [anon_sym_DQUOTE] = ACTIONS(29),
    [anon_sym_SQUOTE] = ACTIONS(29),
    [anon_sym_BQUOTE] = ACTIONS(29),
  },
  [4] = {
    [sym_expressions] = STATE(59),
    [sym__bracket_expression] = STATE(22),
    [sym__quote_expression] = STATE(42),
    [sym_paren_expression] = STATE(22),
    [sym_brace_expression] = STATE(22),
    [sym_bracket_expression] = STATE(22),
    [sym_double_quote_expression] = STATE(42),
    [sym_single_quote_expression] = STATE(42),
    [sym_backtick_quote_expression] = STATE(42),
    [aux_sym_expressions_repeat1] = STATE(22),
    [aux_sym_expressions_repeat2] = STATE(42),
    [sym__base_expression] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_RPAREN] = ACTIONS(31),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_RBRACE] = ACTIONS(31),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_RBRACK] = ACTIONS(31),
    [anon_sym_DQUOTE] = ACTIONS(31),
    [anon_sym_SQUOTE] = ACTIONS(31),
    [anon_sym_BQUOTE] = ACTIONS(31),
  },
  [5] = {
    [sym_expressions] = STATE(56),
    [sym__bracket_expression] = STATE(22),
    [sym__quote_expression] = STATE(24),
    [sym_paren_expression] = STATE(22),
    [sym_brace_expression] = STATE(22),
    [sym_bracket_expression] = STATE(22),
    [sym_double_quote_expression] = STATE(24),
    [sym_single_quote_expression] = STATE(24),
    [sym_backtick_quote_expression] = STATE(24),
    [aux_sym_expressions_repeat1] = STATE(22),
    [aux_sym_expressions_repeat2] = STATE(24),
    [sym__base_expression] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_RBRACK] = ACTIONS(33),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [anon_sym_SQUOTE] = ACTIONS(37),
    [anon_sym_BQUOTE] = ACTIONS(39),
  },
  [6] = {
    [sym_expressions] = STATE(52),
    [sym__bracket_expression] = STATE(22),
    [sym__quote_expression] = STATE(24),
    [sym_paren_expression] = STATE(22),
    [sym_brace_expression] = STATE(22),
    [sym_bracket_expression] = STATE(22),
    [sym_double_quote_expression] = STATE(24),
    [sym_single_quote_expression] = STATE(24),
    [sym_backtick_quote_expression] = STATE(24),
    [aux_sym_expressions_repeat1] = STATE(22),
    [aux_sym_expressions_repeat2] = STATE(24),
    [sym__base_expression] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_RPAREN] = ACTIONS(41),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [anon_sym_SQUOTE] = ACTIONS(37),
    [anon_sym_BQUOTE] = ACTIONS(39),
  },
  [7] = {
    [sym_expressions] = STATE(50),
    [sym__bracket_expression] = STATE(22),
    [sym__quote_expression] = STATE(24),
    [sym_paren_expression] = STATE(22),
    [sym_brace_expression] = STATE(22),
    [sym_bracket_expression] = STATE(22),
    [sym_double_quote_expression] = STATE(24),
    [sym_single_quote_expression] = STATE(24),
    [sym_backtick_quote_expression] = STATE(24),
    [aux_sym_expressions_repeat1] = STATE(22),
    [aux_sym_expressions_repeat2] = STATE(24),
    [sym__base_expression] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_RBRACE] = ACTIONS(43),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [anon_sym_SQUOTE] = ACTIONS(37),
    [anon_sym_BQUOTE] = ACTIONS(39),
  },
  [8] = {
    [sym_expressions] = STATE(48),
    [sym__bracket_expression] = STATE(22),
    [sym__quote_expression] = STATE(24),
    [sym_paren_expression] = STATE(22),
    [sym_brace_expression] = STATE(22),
    [sym_bracket_expression] = STATE(22),
    [sym_double_quote_expression] = STATE(24),
    [sym_single_quote_expression] = STATE(24),
    [sym_backtick_quote_expression] = STATE(24),
    [aux_sym_expressions_repeat1] = STATE(22),
    [aux_sym_expressions_repeat2] = STATE(24),
    [sym__base_expression] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_RBRACK] = ACTIONS(45),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [anon_sym_SQUOTE] = ACTIONS(37),
    [anon_sym_BQUOTE] = ACTIONS(39),
  },
  [9] = {
    [sym_expressions] = STATE(59),
    [sym__bracket_expression] = STATE(22),
    [sym__quote_expression] = STATE(42),
    [sym_paren_expression] = STATE(22),
    [sym_brace_expression] = STATE(22),
    [sym_bracket_expression] = STATE(22),
    [sym_double_quote_expression] = STATE(42),
    [sym_single_quote_expression] = STATE(42),
    [sym_backtick_quote_expression] = STATE(42),
    [aux_sym_expressions_repeat1] = STATE(22),
    [aux_sym_expressions_repeat2] = STATE(42),
    [ts_builtin_sym_end] = ACTIONS(47),
    [sym__base_expression] = ACTIONS(47),
    [anon_sym_LPAREN] = ACTIONS(31),
    [anon_sym_LBRACE] = ACTIONS(31),
    [anon_sym_LBRACK] = ACTIONS(31),
    [anon_sym_DQUOTE] = ACTIONS(31),
    [anon_sym_SQUOTE] = ACTIONS(31),
    [anon_sym_BQUOTE] = ACTIONS(31),
  },
  [10] = {
    [sym_expressions] = STATE(58),
    [sym__bracket_expression] = STATE(22),
    [sym__quote_expression] = STATE(43),
    [sym_paren_expression] = STATE(22),
    [sym_brace_expression] = STATE(22),
    [sym_bracket_expression] = STATE(22),
    [sym_double_quote_expression] = STATE(43),
    [sym_single_quote_expression] = STATE(43),
    [sym_backtick_quote_expression] = STATE(43),
    [aux_sym_expressions_repeat1] = STATE(22),
    [aux_sym_expressions_repeat2] = STATE(43),
    [ts_builtin_sym_end] = ACTIONS(49),
    [sym__base_expression] = ACTIONS(49),
    [anon_sym_LPAREN] = ACTIONS(29),
    [anon_sym_LBRACE] = ACTIONS(29),
    [anon_sym_LBRACK] = ACTIONS(29),
    [anon_sym_DQUOTE] = ACTIONS(29),
    [anon_sym_SQUOTE] = ACTIONS(29),
    [anon_sym_BQUOTE] = ACTIONS(29),
  },
  [11] = {
    [sym_expressions] = STATE(57),
    [sym__bracket_expression] = STATE(22),
    [sym__quote_expression] = STATE(34),
    [sym_paren_expression] = STATE(22),
    [sym_brace_expression] = STATE(22),
    [sym_bracket_expression] = STATE(22),
    [sym_double_quote_expression] = STATE(34),
    [sym_single_quote_expression] = STATE(34),
    [sym_backtick_quote_expression] = STATE(34),
    [aux_sym_expressions_repeat1] = STATE(22),
    [aux_sym_expressions_repeat2] = STATE(34),
    [ts_builtin_sym_end] = ACTIONS(51),
    [sym__base_expression] = ACTIONS(51),
    [anon_sym_LPAREN] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(23),
    [anon_sym_LBRACK] = ACTIONS(23),
    [anon_sym_DQUOTE] = ACTIONS(23),
    [anon_sym_SQUOTE] = ACTIONS(23),
    [anon_sym_BQUOTE] = ACTIONS(23),
  },
  [12] = {
    [sym_expressions] = STATE(55),
    [sym__bracket_expression] = STATE(22),
    [sym__quote_expression] = STATE(24),
    [sym_paren_expression] = STATE(22),
    [sym_brace_expression] = STATE(22),
    [sym_bracket_expression] = STATE(22),
    [sym_double_quote_expression] = STATE(24),
    [sym_single_quote_expression] = STATE(24),
    [sym_backtick_quote_expression] = STATE(24),
    [aux_sym_expressions_repeat1] = STATE(22),
    [aux_sym_expressions_repeat2] = STATE(24),
    [sym__base_expression] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_RBRACE] = ACTIONS(53),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [anon_sym_SQUOTE] = ACTIONS(37),
    [anon_sym_BQUOTE] = ACTIONS(39),
  },
  [13] = {
    [sym_expressions] = STATE(54),
    [sym__bracket_expression] = STATE(22),
    [sym__quote_expression] = STATE(24),
    [sym_paren_expression] = STATE(22),
    [sym_brace_expression] = STATE(22),
    [sym_bracket_expression] = STATE(22),
    [sym_double_quote_expression] = STATE(24),
    [sym_single_quote_expression] = STATE(24),
    [sym_backtick_quote_expression] = STATE(24),
    [aux_sym_expressions_repeat1] = STATE(22),
    [aux_sym_expressions_repeat2] = STATE(24),
    [sym__base_expression] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_RPAREN] = ACTIONS(55),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [anon_sym_SQUOTE] = ACTIONS(37),
    [anon_sym_BQUOTE] = ACTIONS(39),
  },
  [14] = {
    [sym_expressions] = STATE(59),
    [sym__bracket_expression] = STATE(22),
    [sym__quote_expression] = STATE(42),
    [sym_paren_expression] = STATE(22),
    [sym_brace_expression] = STATE(22),
    [sym_bracket_expression] = STATE(22),
    [sym_double_quote_expression] = STATE(42),
    [sym_single_quote_expression] = STATE(42),
    [sym_backtick_quote_expression] = STATE(42),
    [aux_sym_expressions_repeat1] = STATE(22),
    [aux_sym_expressions_repeat2] = STATE(42),
    [sym__base_expression] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [anon_sym_SQUOTE] = ACTIONS(37),
    [anon_sym_BQUOTE] = ACTIONS(57),
  },
  [15] = {
    [sym_expressions] = STATE(47),
    [sym__bracket_expression] = STATE(22),
    [sym__quote_expression] = STATE(34),
    [sym_paren_expression] = STATE(22),
    [sym_brace_expression] = STATE(22),
    [sym_bracket_expression] = STATE(22),
    [sym_double_quote_expression] = STATE(34),
    [sym_single_quote_expression] = STATE(34),
    [sym_backtick_quote_expression] = STATE(34),
    [aux_sym_expressions_repeat1] = STATE(22),
    [aux_sym_expressions_repeat2] = STATE(34),
    [sym__base_expression] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_DQUOTE] = ACTIONS(59),
    [anon_sym_SQUOTE] = ACTIONS(37),
    [anon_sym_BQUOTE] = ACTIONS(39),
  },
  [16] = {
    [sym_expressions] = STATE(57),
    [sym__bracket_expression] = STATE(22),
    [sym__quote_expression] = STATE(34),
    [sym_paren_expression] = STATE(22),
    [sym_brace_expression] = STATE(22),
    [sym_bracket_expression] = STATE(22),
    [sym_double_quote_expression] = STATE(34),
    [sym_single_quote_expression] = STATE(34),
    [sym_backtick_quote_expression] = STATE(34),
    [aux_sym_expressions_repeat1] = STATE(22),
    [aux_sym_expressions_repeat2] = STATE(34),
    [sym__base_expression] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_DQUOTE] = ACTIONS(61),
    [anon_sym_SQUOTE] = ACTIONS(37),
    [anon_sym_BQUOTE] = ACTIONS(39),
  },
  [17] = {
    [sym_expressions] = STATE(58),
    [sym__bracket_expression] = STATE(22),
    [sym__quote_expression] = STATE(43),
    [sym_paren_expression] = STATE(22),
    [sym_brace_expression] = STATE(22),
    [sym_bracket_expression] = STATE(22),
    [sym_double_quote_expression] = STATE(43),
    [sym_single_quote_expression] = STATE(43),
    [sym_backtick_quote_expression] = STATE(43),
    [aux_sym_expressions_repeat1] = STATE(22),
    [aux_sym_expressions_repeat2] = STATE(43),
    [sym__base_expression] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [anon_sym_SQUOTE] = ACTIONS(63),
    [anon_sym_BQUOTE] = ACTIONS(39),
  },
  [18] = {
    [sym__expression] = STATE(19),
    [sym__bracket_expression] = STATE(19),
    [sym__quote_expression] = STATE(19),
    [sym_paren_expression] = STATE(19),
    [sym_brace_expression] = STATE(19),
    [sym_bracket_expression] = STATE(19),
    [sym_double_quote_expression] = STATE(19),
    [sym_single_quote_expression] = STATE(19),
    [sym_backtick_quote_expression] = STATE(19),
    [aux_sym_source_file_repeat1] = STATE(19),
    [ts_builtin_sym_end] = ACTIONS(65),
    [sym__base_expression] = ACTIONS(67),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_LBRACK] = ACTIONS(11),
    [anon_sym_DQUOTE] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_BQUOTE] = ACTIONS(17),
  },
  [19] = {
    [sym__expression] = STATE(19),
    [sym__bracket_expression] = STATE(19),
    [sym__quote_expression] = STATE(19),
    [sym_paren_expression] = STATE(19),
    [sym_brace_expression] = STATE(19),
    [sym_bracket_expression] = STATE(19),
    [sym_double_quote_expression] = STATE(19),
    [sym_single_quote_expression] = STATE(19),
    [sym_backtick_quote_expression] = STATE(19),
    [aux_sym_source_file_repeat1] = STATE(19),
    [ts_builtin_sym_end] = ACTIONS(69),
    [sym__base_expression] = ACTIONS(71),
    [anon_sym_LPAREN] = ACTIONS(74),
    [anon_sym_LBRACE] = ACTIONS(77),
    [anon_sym_LBRACK] = ACTIONS(80),
    [anon_sym_DQUOTE] = ACTIONS(83),
    [anon_sym_SQUOTE] = ACTIONS(86),
    [anon_sym_BQUOTE] = ACTIONS(89),
  },
  [20] = {
    [sym_expressions] = STATE(51),
    [sym__bracket_expression] = STATE(22),
    [sym__quote_expression] = STATE(42),
    [sym_paren_expression] = STATE(22),
    [sym_brace_expression] = STATE(22),
    [sym_bracket_expression] = STATE(22),
    [sym_double_quote_expression] = STATE(42),
    [sym_single_quote_expression] = STATE(42),
    [sym_backtick_quote_expression] = STATE(42),
    [aux_sym_expressions_repeat1] = STATE(22),
    [aux_sym_expressions_repeat2] = STATE(42),
    [sym__base_expression] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [anon_sym_SQUOTE] = ACTIONS(37),
    [anon_sym_BQUOTE] = ACTIONS(92),
  },
  [21] = {
    [sym_expressions] = STATE(49),
    [sym__bracket_expression] = STATE(22),
    [sym__quote_expression] = STATE(43),
    [sym_paren_expression] = STATE(22),
    [sym_brace_expression] = STATE(22),
    [sym_bracket_expression] = STATE(22),
    [sym_double_quote_expression] = STATE(43),
    [sym_single_quote_expression] = STATE(43),
    [sym_backtick_quote_expression] = STATE(43),
    [aux_sym_expressions_repeat1] = STATE(22),
    [aux_sym_expressions_repeat2] = STATE(43),
    [sym__base_expression] = ACTIONS(19),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_DQUOTE] = ACTIONS(35),
    [anon_sym_SQUOTE] = ACTIONS(94),
    [anon_sym_BQUOTE] = ACTIONS(39),
  },
  [22] = {
    [sym__bracket_expression] = STATE(23),
    [sym_paren_expression] = STATE(23),
    [sym_brace_expression] = STATE(23),
    [sym_bracket_expression] = STATE(23),
    [aux_sym_expressions_repeat1] = STATE(23),
    [sym__base_expression] = ACTIONS(96),
    [anon_sym_LPAREN] = ACTIONS(21),
    [anon_sym_RPAREN] = ACTIONS(98),
    [anon_sym_LBRACE] = ACTIONS(25),
    [anon_sym_RBRACE] = ACTIONS(98),
    [anon_sym_LBRACK] = ACTIONS(27),
    [anon_sym_RBRACK] = ACTIONS(98),
    [anon_sym_DQUOTE] = ACTIONS(98),
    [anon_sym_SQUOTE] = ACTIONS(98),
    [anon_sym_BQUOTE] = ACTIONS(98),
  },
  [23] = {
    [sym__bracket_expression] = STATE(23),
    [sym_paren_expression] = STATE(23),
    [sym_brace_expression] = STATE(23),
    [sym_bracket_expression] = STATE(23),
    [aux_sym_expressions_repeat1] = STATE(23),
    [sym__base_expression] = ACTIONS(100),
    [anon_sym_LPAREN] = ACTIONS(103),
    [anon_sym_RPAREN] = ACTIONS(106),
    [anon_sym_LBRACE] = ACTIONS(108),
    [anon_sym_RBRACE] = ACTIONS(106),
    [anon_sym_LBRACK] = ACTIONS(111),
    [anon_sym_RBRACK] = ACTIONS(106),
    [anon_sym_DQUOTE] = ACTIONS(106),
    [anon_sym_SQUOTE] = ACTIONS(106),
    [anon_sym_BQUOTE] = ACTIONS(106),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(116), 1,
      anon_sym_DQUOTE,
    ACTIONS(118), 1,
      anon_sym_SQUOTE,
    ACTIONS(120), 1,
      anon_sym_BQUOTE,
    ACTIONS(114), 3,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
    STATE(25), 5,
      sym__quote_expression,
      sym_double_quote_expression,
      sym_single_quote_expression,
      sym_backtick_quote_expression,
      aux_sym_expressions_repeat2,
  [22] = 5,
    ACTIONS(124), 1,
      anon_sym_DQUOTE,
    ACTIONS(127), 1,
      anon_sym_SQUOTE,
    ACTIONS(130), 1,
      anon_sym_BQUOTE,
    ACTIONS(122), 3,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
    STATE(25), 5,
      sym__quote_expression,
      sym_double_quote_expression,
      sym_single_quote_expression,
      sym_backtick_quote_expression,
      aux_sym_expressions_repeat2,
  [44] = 2,
    ACTIONS(133), 1,
      sym__base_expression,
    ACTIONS(135), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [59] = 2,
    ACTIONS(137), 1,
      sym__base_expression,
    ACTIONS(139), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [74] = 2,
    ACTIONS(141), 1,
      sym__base_expression,
    ACTIONS(143), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [89] = 2,
    ACTIONS(145), 1,
      sym__base_expression,
    ACTIONS(147), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [104] = 2,
    ACTIONS(149), 1,
      sym__base_expression,
    ACTIONS(151), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [119] = 2,
    ACTIONS(153), 1,
      sym__base_expression,
    ACTIONS(155), 9,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [134] = 2,
    ACTIONS(157), 2,
      ts_builtin_sym_end,
      sym__base_expression,
    ACTIONS(159), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [147] = 2,
    ACTIONS(145), 2,
      ts_builtin_sym_end,
      sym__base_expression,
    ACTIONS(147), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [160] = 4,
    ACTIONS(114), 1,
      anon_sym_DQUOTE,
    ACTIONS(118), 1,
      anon_sym_SQUOTE,
    ACTIONS(120), 1,
      anon_sym_BQUOTE,
    STATE(25), 5,
      sym__quote_expression,
      sym_double_quote_expression,
      sym_single_quote_expression,
      sym_backtick_quote_expression,
      aux_sym_expressions_repeat2,
  [177] = 2,
    ACTIONS(161), 2,
      ts_builtin_sym_end,
      sym__base_expression,
    ACTIONS(163), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [190] = 2,
    ACTIONS(153), 2,
      ts_builtin_sym_end,
      sym__base_expression,
    ACTIONS(155), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [203] = 2,
    ACTIONS(133), 2,
      ts_builtin_sym_end,
      sym__base_expression,
    ACTIONS(135), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [216] = 2,
    ACTIONS(137), 2,
      ts_builtin_sym_end,
      sym__base_expression,
    ACTIONS(139), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [229] = 2,
    ACTIONS(141), 2,
      ts_builtin_sym_end,
      sym__base_expression,
    ACTIONS(143), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [242] = 2,
    ACTIONS(165), 2,
      ts_builtin_sym_end,
      sym__base_expression,
    ACTIONS(167), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [255] = 2,
    ACTIONS(149), 2,
      ts_builtin_sym_end,
      sym__base_expression,
    ACTIONS(151), 6,
      anon_sym_LPAREN,
      anon_sym_LBRACE,
      anon_sym_LBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [268] = 4,
    ACTIONS(114), 1,
      anon_sym_BQUOTE,
    ACTIONS(116), 1,
      anon_sym_DQUOTE,
    ACTIONS(118), 1,
      anon_sym_SQUOTE,
    STATE(25), 5,
      sym__quote_expression,
      sym_double_quote_expression,
      sym_single_quote_expression,
      sym_backtick_quote_expression,
      aux_sym_expressions_repeat2,
  [285] = 4,
    ACTIONS(114), 1,
      anon_sym_SQUOTE,
    ACTIONS(116), 1,
      anon_sym_DQUOTE,
    ACTIONS(120), 1,
      anon_sym_BQUOTE,
    STATE(25), 5,
      sym__quote_expression,
      sym_double_quote_expression,
      sym_single_quote_expression,
      sym_backtick_quote_expression,
      aux_sym_expressions_repeat2,
  [302] = 1,
    ACTIONS(165), 6,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [311] = 1,
    ACTIONS(161), 6,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [320] = 1,
    ACTIONS(157), 6,
      anon_sym_RPAREN,
      anon_sym_RBRACE,
      anon_sym_RBRACK,
      anon_sym_DQUOTE,
      anon_sym_SQUOTE,
      anon_sym_BQUOTE,
  [329] = 1,
    ACTIONS(169), 1,
      anon_sym_DQUOTE,
  [333] = 1,
    ACTIONS(171), 1,
      anon_sym_RBRACK,
  [337] = 1,
    ACTIONS(173), 1,
      anon_sym_SQUOTE,
  [341] = 1,
    ACTIONS(175), 1,
      anon_sym_RBRACE,
  [345] = 1,
    ACTIONS(177), 1,
      anon_sym_BQUOTE,
  [349] = 1,
    ACTIONS(179), 1,
      anon_sym_RPAREN,
  [353] = 1,
    ACTIONS(181), 1,
      ts_builtin_sym_end,
  [357] = 1,
    ACTIONS(183), 1,
      anon_sym_RPAREN,
  [361] = 1,
    ACTIONS(185), 1,
      anon_sym_RBRACE,
  [365] = 1,
    ACTIONS(187), 1,
      anon_sym_RBRACK,
  [369] = 1,
    ACTIONS(189), 1,
      anon_sym_DQUOTE,
  [373] = 1,
    ACTIONS(191), 1,
      anon_sym_SQUOTE,
  [377] = 1,
    ACTIONS(193), 1,
      anon_sym_BQUOTE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(24)] = 0,
  [SMALL_STATE(25)] = 22,
  [SMALL_STATE(26)] = 44,
  [SMALL_STATE(27)] = 59,
  [SMALL_STATE(28)] = 74,
  [SMALL_STATE(29)] = 89,
  [SMALL_STATE(30)] = 104,
  [SMALL_STATE(31)] = 119,
  [SMALL_STATE(32)] = 134,
  [SMALL_STATE(33)] = 147,
  [SMALL_STATE(34)] = 160,
  [SMALL_STATE(35)] = 177,
  [SMALL_STATE(36)] = 190,
  [SMALL_STATE(37)] = 203,
  [SMALL_STATE(38)] = 216,
  [SMALL_STATE(39)] = 229,
  [SMALL_STATE(40)] = 242,
  [SMALL_STATE(41)] = 255,
  [SMALL_STATE(42)] = 268,
  [SMALL_STATE(43)] = 285,
  [SMALL_STATE(44)] = 302,
  [SMALL_STATE(45)] = 311,
  [SMALL_STATE(46)] = 320,
  [SMALL_STATE(47)] = 329,
  [SMALL_STATE(48)] = 333,
  [SMALL_STATE(49)] = 337,
  [SMALL_STATE(50)] = 341,
  [SMALL_STATE(51)] = 345,
  [SMALL_STATE(52)] = 349,
  [SMALL_STATE(53)] = 353,
  [SMALL_STATE(54)] = 357,
  [SMALL_STATE(55)] = 361,
  [SMALL_STATE(56)] = 365,
  [SMALL_STATE(57)] = 369,
  [SMALL_STATE(58)] = 373,
  [SMALL_STATE(59)] = 377,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_double_quote_expression, 2),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_single_quote_expression, 2),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_backtick_quote_expression, 2),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [41] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_backtick_quote_expression, 2),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_single_quote_expression, 2),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_double_quote_expression, 2),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(19),
  [74] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(6),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(7),
  [80] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(8),
  [83] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(15),
  [86] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(21),
  [89] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(20),
  [92] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expressions, 1),
  [100] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expressions_repeat1, 2), SHIFT_REPEAT(23),
  [103] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expressions_repeat1, 2), SHIFT_REPEAT(13),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_expressions_repeat1, 2),
  [108] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expressions_repeat1, 2), SHIFT_REPEAT(12),
  [111] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_expressions_repeat1, 2), SHIFT_REPEAT(5),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expressions, 1),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_expressions_repeat2, 2),
  [124] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expressions_repeat2, 2), SHIFT_REPEAT(16),
  [127] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expressions_repeat2, 2), SHIFT_REPEAT(17),
  [130] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_expressions_repeat2, 2), SHIFT_REPEAT(14),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bracket_expression, 3),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bracket_expression, 3),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_brace_expression, 3),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_brace_expression, 3),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paren_expression, 3),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paren_expression, 3),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_brace_expression, 2),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_brace_expression, 2),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bracket_expression, 2),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bracket_expression, 2),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paren_expression, 2),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paren_expression, 2),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_double_quote_expression, 3),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_double_quote_expression, 3),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_backtick_quote_expression, 3),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_backtick_quote_expression, 3),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_single_quote_expression, 3),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_single_quote_expression, 3),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [181] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_yard(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
