// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BufferChange = { buffer_id: string, start_line: number, end_line: number, content: string, version: number, message_id: number, retry_count: number, };
