// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Position } from "./Position";

export type CursorParams = { buffer_id: string, anchors: Array<Position>, actives: Array<Position>, };
