// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticSeverity } from "./DiagnosticSeverity";
import type { Range } from "./Range";

export type Diagnostic = { range: Range, message: string, severity: DiagnosticSeverity | null, };
