// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EditorAction = "undo" | "redo" | "save" | "forceSave" | "copy" | "cut" | "paste" | "selectAll";
