// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorAction } from "./EditorAction";

export type EditorActionParams = { action: EditorAction; buffer_id: string | null };
