// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BufferDiagnostics } from "./BufferDiagnostics";
import type { BufferDiffParams } from "./BufferDiffParams";
import type { BufferParams } from "./BufferParams";
import type { EditorActionParams } from "./EditorActionParams";
import type { KeyboardParams } from "./KeyboardParams";
import type { SearchParams } from "./SearchParams";
import type { SelectionModeParams } from "./SelectionModeParams";
import type { SelectionSet } from "./SelectionSet";
import type { TypedModeParams } from "./TypedModeParams";
import type { ViewportParams } from "./ViewportParams";

export type InputMessage =
    | { tag: "ping"; params: string | null }
    | { tag: "buffer.open"; params: BufferParams }
    | { tag: "buffer.close"; params: BufferParams }
    | { tag: "buffer.save"; params: BufferParams }
    | { tag: "buffer.change"; params: BufferDiffParams }
    | { tag: "buffer.active"; params: BufferParams }
    | { tag: "selection.set"; params: SelectionSet }
    | { tag: "mode.set"; params: TypedModeParams }
    | { tag: "selection_mode.set"; params: SelectionModeParams }
    | { tag: "keyboard.input"; params: KeyboardParams }
    | { tag: "editor.action"; params: EditorActionParams }
    | { tag: "search.find"; params: SearchParams }
    | { tag: "viewport.change"; params: ViewportParams }
    | { tag: "diagnostics.change"; params: Array<BufferDiagnostics> };
