// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InputMessage } from "./InputMessage";

export type InputMessageWrapper = { message: InputMessage; id: number };
