// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BufferChange } from "./BufferChange";
import type { BufferParams } from "./BufferParams";
import type { CursorParams } from "./CursorParams";
import type { KeyboardParams } from "./KeyboardParams";
import type { ModeParams } from "./ModeParams";
import type { SearchParams } from "./SearchParams";
import type { SelectionSet } from "./SelectionSet";

export type InputMessage = { "tag": "buffer.open", "params": BufferParams } | { "tag": "buffer.close", "params": BufferParams } | { "tag": "buffer.save", "params": BufferParams } | { "tag": "buffer.change", "params": BufferChange } | { "tag": "buffer.active", "params": BufferParams } | { "tag": "cursor.update", "params": CursorParams } | { "tag": "cursor.get" } | { "tag": "selection.set", "params": SelectionSet } | { "tag": "selection.get" } | { "tag": "mode.set", "params": ModeParams } | { "tag": "selection_mode.set", "params": ModeParams } | { "tag": "keyboard.input", "params": KeyboardParams } | { "tag": "search.find", "params": SearchParams } | { "tag": "ping", "params": string | null };
