// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BufferChange } from "./BufferChange";
import type { BufferParams } from "./BufferParams";
import type { CommandParams } from "./CommandParams";
import type { CursorParams } from "./CursorParams";
import type { LogParams } from "./LogParams";
import type { ModeParams } from "./ModeParams";
import type { SelectionSet } from "./SelectionSet";

export type OutputMessage = { "tag": "buffer.open", "params": BufferParams } | { "tag": "buffer.close", "params": BufferParams } | { "tag": "buffer.save", "params": BufferParams } | { "tag": "buffer.change", "params": BufferChange } | { "tag": "buffer.update", "params": BufferChange } | { "tag": "buffer.diff", "params": BufferChange } | { "tag": "buffer.ack", "params": bigint } | { "tag": "cursor.update", "params": CursorParams } | { "tag": "selection.update", "params": SelectionSet } | { "tag": "mode.change", "params": ModeParams } | { "tag": "selection_mode.change", "params": ModeParams } | { "tag": "command", "params": CommandParams } | { "tag": "ki.log", "params": LogParams } | { "tag": "ping", "params": string } | { "tag": "error", "params": string } | { "tag": "search.results", "params": string } | { "tag": "success", "params": boolean };
