// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutputMessage } from "./OutputMessage";
import type { ResponseError } from "./ResponseError";

export type OutputMessageWrapper = { message: OutputMessage; id: number; error?: ResponseError };
