// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SearchParams = { buffer_id: string, query: string, case_sensitive: boolean, whole_word: boolean, regex: boolean, };
