// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiagnosticKind } from "./DiagnosticKind";

export type SelectionMode = { "type": "Character" } | { "type": "Line" } | { "type": "LineFull" } | { "type": "Word" } | { "type": "WordFine" } | { "type": "Token" } | { "type": "Custom" } | { "type": "SyntaxNode" } | { "type": "SyntaxNodeFine" } | { "type": "Mark" } | { "type": "Find", "params": { search: string, } } | { "type": "Diagnostic", "params": DiagnosticKind } | { "type": "GitHunk" } | { "type": "LocalQuickfix" };
