// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Selection } from "./Selection";

export type SelectionSet = { buffer_id: string; primary: number; selections: Array<Selection> };
