// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SelectionMode =
    | { type: "Character" }
    | { type: "Line" }
    | { type: "LineFull" }
    | { type: "word" }
    | { type: "fine_word" }
    | { type: "Token" }
    | { type: "Custom" }
    | { type: "SyntaxNode" }
    | { type: "SyntaxNodeFine" }
    | { type: "Mark" }
    | { type: "Find" }
    | { type: "Diagnostic" }
    | { type: "GitHunk" }
    | { type: "LocalQuickfix" };
