/*
 Generated by typeshare 1.7.0
*/

export interface Position {
	line: number;
	character: number;
}

export interface Range {
	start: Position;
	end: Position;
}

export interface Selection {
	/** The other end of the selection */
	anchor: Position;
	/** The cursor position */
	active: Position;
	is_extended?: boolean;
}

export interface SelectionSetParams {
	uri?: string;
	selections: Selection[];
}

/** Represents a single text edit operation. */
export interface DiffEdit {
	/** The range of the text to be replaced. */
	range: Range;
	/** The new text to replace the range. */
	new_text: string;
}

export interface BufferParams {
	uri: string;
}

export interface SyncBufferResponseParams {
	uri: string;
	content: string;
}

export interface BufferOpenParams {
	uri: string;
	selections: Selection[];
	content: string;
}

export interface BufferDiffParams {
	buffer_id: string;
	edits: DiffEdit[];
}

export enum EditorMode {
	Normal = "normal",
	Insert = "insert",
	MultiCursor = "multiCursor",
	FindOneChar = "findOneChar",
	Swap = "swap",
	Replace = "replace",
	Delete = "delete",
}

export interface ModeParams {
	mode: EditorMode;
	buffer_id?: string;
}

export type SelectionMode = 
	| { tag: "Character", params?: undefined }
	| { tag: "Line", params?: undefined }
	| { tag: "LineFull", params?: undefined }
	| { tag: "Subword", params?: undefined }
	| { tag: "Word", params?: undefined }
	| { tag: "Custom", params?: undefined }
	| { tag: "SyntaxNode", params?: undefined }
	| { tag: "SyntaxNodeFine", params?: undefined }
	| { tag: "Mark", params?: undefined }
	| { tag: "Find", params: {
	search: string;
}}
	| { tag: "Diagnostic", params: DiagnosticKind }
	| { tag: "GitHunk", params?: undefined }
	| { tag: "LocalQuickfix", params?: undefined };

export interface SelectionModeParams {
	mode: SelectionMode;
	buffer_id?: string;
}

export interface LineRange {
	start: number;
	end: number;
}

export interface ViewportParams {
	buffer_id: string;
	visible_line_ranges: LineRange[];
}

export interface KeyboardParams {
	key: string;
	uri: string;
	/**
	 * This is necessary for resolving buffer content desync
	 * between Ki and the host application
	 */
	content_hash: number;
}

export enum DiagnosticSeverity {
	Warning = "Warning",
	Hint = "Hint",
	Information = "Information",
	Error = "Error",
}

export interface Diagnostic {
	range: Range;
	message: string;
	severity?: DiagnosticSeverity;
}

export interface BufferDiagnostics {
	path: string;
	diagnostics: Diagnostic[];
}

export interface PromptItem {
	label: string;
	details?: string;
}

export interface PromptOpenedParams {
	title: string;
	items: PromptItem[];
}

export interface JumpTarget {
	key: string;
	position: Position;
}

export interface JumpsParams {
	uri: string;
	targets: JumpTarget[];
}

export interface MarksParams {
	uri: string;
	marks: Range[];
}

export type InputMessage = 
	| { tag: "ping", params?: string }
	| { tag: "buffer.open", params: BufferOpenParams }
	| { tag: "buffer.change", params: BufferDiffParams }
	| { tag: "buffer.active", params: BufferParams }
	| { tag: "editor.syncBufferResponse", params: SyncBufferResponseParams }
	| { tag: "selection.set", params: SelectionSetParams }
	| { tag: "keyboard.input", params: KeyboardParams }
	| { tag: "viewport.change", params: ViewportParams }
	| { tag: "diagnostics.change", params: BufferDiagnostics[] }
	| { tag: "prompt.enter", params: string };

export interface InputMessageWrapper {
	message: InputMessage;
	id: number;
}

export type OutputMessage = 
	| { tag: "ping", params: string }
	| { tag: "error", params: string }
	/**
	 * TODO: handle this on VS Code side
	 * See https://code.visualstudio.com/api/extension-guides/virtual-documents
	 */
	| { tag: "buffer.open", params: BufferParams }
	| { tag: "buffer.save", params: BufferParams }
	| { tag: "buffer.diff", params: BufferDiffParams }
	| { tag: "selection.update", params: SelectionSetParams }
	| { tag: "mode.change", params: ModeParams }
	| { tag: "selection_mode.change", params: SelectionModeParams }
	| { tag: "viewport.change", params: ViewportParams }
	| { tag: "prompt.opened", params: PromptOpenedParams }
	| { tag: "editor.jump", params: JumpsParams }
	| { tag: "editor.mark", params: MarksParams }
	| { tag: "lsp.definition", params?: undefined }
	| { tag: "lsp.hover", params?: undefined }
	| { tag: "lsp.references", params?: undefined }
	| { tag: "lsp.declaration", params?: undefined }
	| { tag: "lsp.typeDefinition", params?: undefined }
	| { tag: "lsp.implementation", params?: undefined }
	| { tag: "editor.keyboardLayout", params: string }
	| { tag: "lsp.rename", params?: undefined }
	| { tag: "lsp.codeAction", params?: undefined }
	| { tag: "lsp.documentSymbols", params?: undefined }
	| { tag: "lsp.workspaceSymbols", params?: undefined }
	| { tag: "editor.syncBufferRequest", params: {
	uri: string;
}}
	| { tag: "editor.showInfo", params: {
	info?: string;
}};

export interface ResponseError {
	code: number;
	message: string;
}

export interface OutputMessageWrapper {
	message: OutputMessage;
	id: number;
	error?: ResponseError;
}

export enum DiagnosticKind {
	Error = "Error",
	Information = "Information",
	Warning = "Warning",
	All = "All",
	Hint = "Hint",
}

