// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorMode } from "./EditorMode";

export type TypedModeParams = { mode: EditorMode; buffer_id: string | null };
