// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ViewportParams = { buffer_id: string; visible_line_ranges: Array<[number, number]> };
