/**
 * Generated by typeshare 1.11.0
 */

package com.kieditor.protocol

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

/// VS Code Position
@Serializable
data class Position (
	val line: UInt,
	val character: UInt
)

@Serializable
data class Range (
	val start: Position,
	val end: Position
)

@Serializable
enum class DiagnosticSeverity(val string: String) {
	@SerialName("Warning")
	Warning("Warning"),
	@SerialName("Hint")
	Hint("Hint"),
	@SerialName("Information")
	Information("Information"),
	@SerialName("Error")
	Error("Error"),
}

@Serializable
data class Diagnostic (
	val range: Range,
	val message: String,
	val severity: DiagnosticSeverity? = null
)

@Serializable
data class BufferDiagnostics (
	val path: String,
	val diagnostics: List<Diagnostic>
)

@Serializable
data class DiffEdit (
	val range: Range,
	val new_text: String
)

@Serializable
data class BufferDiffParams (
	val buffer_id: String,
	val edits: List<DiffEdit>
)

@Serializable
data class BufferParams (
	val uri: String,
	val content: String? = null,
	val language_id: String? = null,
	val version: Int? = null
)

@Serializable
data class CommandParams (
	val name: String,
	val args: List<String>,
	val success: Boolean? = null
)

@Serializable
data class CursorParams (
	val buffer_id: String,
	val anchors: List<Position>,
	val actives: List<Position>
)

@Serializable
enum class EditorAction(val string: String) {
	@SerialName("undo")
	Undo("undo"),
	@SerialName("redo")
	Redo("redo"),
	@SerialName("save")
	Save("save"),
	@SerialName("forceSave")
	ForceSave("forceSave"),
	@SerialName("copy")
	Copy("copy"),
	@SerialName("cut")
	Cut("cut"),
	@SerialName("paste")
	Paste("paste"),
	@SerialName("selectAll")
	SelectAll("selectAll"),
}

@Serializable
data class EditorActionParams (
	val action: EditorAction,
	val buffer_id: String? = null
)

@Serializable
data class ExternalBufferParams (
	val buffer_id: String,
	val content: String
)

@Serializable
sealed class InputMessage {
	@Serializable
	@SerialName("ping")
	data class Ping(val params: String?): InputMessage()
	@Serializable
	@SerialName("buffer.open")
	data class BufferOpen(val params: BufferParams): InputMessage()
	@Serializable
	@SerialName("buffer.close")
	data class BufferClose(val params: BufferParams): InputMessage()
	@Serializable
	@SerialName("buffer.save")
	data class BufferSave(val params: BufferParams): InputMessage()
	@Serializable
	@SerialName("buffer.change")
	data class BufferChange(val params: BufferDiffParams): InputMessage()
	@Serializable
	@SerialName("buffer.active")
	data class BufferActive(val params: BufferParams): InputMessage()
	@Serializable
	@SerialName("selection.set")
	data class SelectionSet(val params: SelectionSet): InputMessage()
	@Serializable
	@SerialName("mode.set")
	data class ModeSet(val params: TypedModeParams): InputMessage()
	@Serializable
	@SerialName("selection_mode.set")
	data class SelectionModeSet(val params: SelectionModeParams): InputMessage()
	@Serializable
	@SerialName("keyboard.input")
	data class KeyboardInput(val params: KeyboardParams): InputMessage()
	@Serializable
	@SerialName("editor.action")
	data class EditorAction(val params: EditorActionParams): InputMessage()
	@Serializable
	@SerialName("search.find")
	data class SearchFind(val params: SearchParams): InputMessage()
	@Serializable
	@SerialName("viewport.change")
	data class ViewportChange(val params: ViewportParams): InputMessage()
	@Serializable
	@SerialName("diagnostics.change")
	data class DiagnosticsChange(val params: List<BufferDiagnostics>): InputMessage()
	@Serializable
	@SerialName("prompt.enter")
	data class PromptEnter(val params: String): InputMessage()
}

@Serializable
data class InputMessageWrapper (
	val message: InputMessage,
	val id: ULong
)

@Serializable
data class JumpTarget (
	val key: String,
	val position: Position
)

@Serializable
data class JumpsParams (
	val uri: String,
	val targets: List<JumpTarget>
)

@Serializable
data class KeyboardParams (
	val key: String,
	val timestamp: ULong,
	val mode: String? = null,
	val is_composed: Boolean
)

@Serializable
data class LineRange (
	val start: UInt,
	val end: UInt
)

@Serializable
data class LogParams (
	val level: String,
	val message: String
)

@Serializable
data class MarksParams (
	val uri: String,
	val marks: List<Range>
)

@Serializable
data class ModeParams (
	val mode: String,
	val buffer_id: String? = null
)

@Serializable
sealed class OutputMessage {
	@Serializable
	@SerialName("ping")
	data class Ping(val params: String): OutputMessage()
	@Serializable
	@SerialName("ki.log")
	data class Log(val params: LogParams): OutputMessage()
	@Serializable
	@SerialName("error")
	data class Error(val params: String): OutputMessage()
	@Serializable
	@SerialName("success")
	data class Success(val params: Boolean): OutputMessage()
	@Serializable
	@SerialName("buffer.open")
	data class BufferOpen(val params: BufferParams): OutputMessage()
	@Serializable
	@SerialName("buffer.close")
	data class BufferClose(val params: BufferParams): OutputMessage()
	@Serializable
	@SerialName("buffer.save")
	data class BufferSave(val params: BufferParams): OutputMessage()
	@Serializable
	@SerialName("buffer.diff")
	data class BufferDiff(val params: BufferDiffParams): OutputMessage()
	@Serializable
	@SerialName("buffer.activated")
	data class BufferActivated(val params: BufferParams): OutputMessage()
	@Serializable
	@SerialName("selection.update")
	data class SelectionUpdate(val params: SelectionSet): OutputMessage()
	@Serializable
	@SerialName("mode.change")
	data class ModeChange(val params: TypedModeParams): OutputMessage()
	@Serializable
	@SerialName("selection_mode.change")
	data class SelectionModeChange(val params: SelectionModeParams): OutputMessage()
	@Serializable
	@SerialName("viewport.change")
	data class ViewportChange(val params: ViewportParams): OutputMessage()
	@Serializable
	@SerialName("external_buffer.created")
	data class ExternalBufferCreated(val params: ExternalBufferParams): OutputMessage()
	@Serializable
	@SerialName("external_buffer.updated")
	data class ExternalBufferUpdated(val params: ExternalBufferParams): OutputMessage()
	@Serializable
	@SerialName("command.executed")
	data class CommandExecuted(val params: CommandParams): OutputMessage()
	@Serializable
	@SerialName("prompt.opened")
	data class PromptOpened(val params: PromptOpenedParams): OutputMessage()
	@Serializable
	@SerialName("search.results")
	data class SearchResults(val params: String): OutputMessage()
	@Serializable
	@SerialName("editor.action")
	data class EditorAction(val params: EditorActionParams): OutputMessage()
	@Serializable
	@SerialName("editor.jump")
	data class JumpsChanged(val params: JumpsParams): OutputMessage()
	@Serializable
	@SerialName("editor.mark")
	data class MarksChanged(val params: MarksParams): OutputMessage()
	@Serializable
	@SerialName("lsp.definition")
	object RequestLspDefinition: OutputMessage()
	@Serializable
	@SerialName("lsp.hover")
	object RequestLspHover: OutputMessage()
	@Serializable
	@SerialName("lsp.references")
	object RequestLspReferences: OutputMessage()
	@Serializable
	@SerialName("lsp.declaration")
	object RequestLspDeclaration: OutputMessage()
	@Serializable
	@SerialName("lsp.typeDefinition")
	object RequestLspTypeDefinition: OutputMessage()
	@Serializable
	@SerialName("lsp.implementation")
	object RequestLspImplementation: OutputMessage()
	@Serializable
	@SerialName("editor.keyboardLayout")
	data class KeyboardLayoutChanged(val params: String): OutputMessage()
}

@Serializable
data class ResponseError (
	val code: Int,
	val message: String,
	val data: Value? = null
)

@Serializable
data class OutputMessageWrapper (
	val message: OutputMessage,
	val id: ULong,
	val error: ResponseError? = null
)

@Serializable
data class PromptItem (
	val label: String,
	val details: String? = null
)

@Serializable
data class PromptOpenedParams (
	val title: String,
	val items: List<PromptItem>
)

@Serializable
data class SearchParams (
	val buffer_id: String,
	val query: String,
	val case_sensitive: Boolean? = null,
	val whole_word: Boolean? = null,
	val regex: Boolean? = null
)

@Serializable
data class Selection (
	val anchor: Position,
	val active: Position,
	val is_extended: Boolean? = null
)

/// Generated type representing the anonymous struct variant `Find` of the `SelectionMode` Rust enum
@Serializable
data class SelectionModeFindInner (
	val search: String
)

@Serializable
sealed class SelectionMode {
	@Serializable
	@SerialName("Character")
	object Character: SelectionMode()
	@Serializable
	@SerialName("Line")
	object Line: SelectionMode()
	@Serializable
	@SerialName("LineFull")
	object LineFull: SelectionMode()
	@Serializable
	@SerialName("Word")
	object Word: SelectionMode()
	@Serializable
	@SerialName("WordFine")
	object WordFine: SelectionMode()
	@Serializable
	@SerialName("Token")
	object Token: SelectionMode()
	@Serializable
	@SerialName("Custom")
	object Custom: SelectionMode()
	@Serializable
	@SerialName("SyntaxNode")
	object SyntaxNode: SelectionMode()
	@Serializable
	@SerialName("SyntaxNodeFine")
	object SyntaxNodeFine: SelectionMode()
	@Serializable
	@SerialName("Mark")
	object Mark: SelectionMode()
	@Serializable
	@SerialName("Find")
	data class Find(val params: SelectionModeFindInner): SelectionMode()
	@Serializable
	@SerialName("Diagnostic")
	data class Diagnostic(val params: DiagnosticKind): SelectionMode()
	@Serializable
	@SerialName("GitHunk")
	object GitHunk: SelectionMode()
	@Serializable
	@SerialName("LocalQuickfix")
	object LocalQuickfix: SelectionMode()
}

@Serializable
data class SelectionModeParams (
	val mode: SelectionMode,
	val buffer_id: String? = null
)

@Serializable
data class SelectionSet (
	val buffer_id: String,
	val primary: UInt? = null,
	val selections: List<Selection>
)

@Serializable
enum class EditorMode(val string: String) {
	@SerialName("normal")
	Normal("normal"),
	@SerialName("insert")
	Insert("insert"),
	@SerialName("multiCursor")
	MultiCursor("multiCursor"),
	@SerialName("findOneChar")
	FindOneChar("findOneChar"),
	@SerialName("swap")
	Swap("swap"),
	@SerialName("replace")
	Replace("replace"),
	@SerialName("extend")
	Extend("extend"),
}

@Serializable
data class TypedModeParams (
	val mode: EditorMode,
	val buffer_id: String? = null
)

@Serializable
data class ViewportParams (
	val buffer_id: String,
	val visible_line_ranges: List<LineRange>
)

@Serializable
enum class DiagnosticKind(val string: String) {
	@SerialName("Error")
	Error("Error"),
	@SerialName("Information")
	Information("Information"),
	@SerialName("Warning")
	Warning("Warning"),
	@SerialName("All")
	All("All"),
	@SerialName("Hint")
	Hint("Hint"),
}

