//! This file is generated by running:
//! ```bash
//! cargo install cargo-typify
//! cargo typify zed_theme/src/zed_theme_schema.json --no-builder
//! ```
#![allow(clippy::redundant_closure_call)]
#![allow(clippy::needless_lifetimes)]
#![allow(clippy::match_single_binding)]
#![allow(clippy::clone_on_copy)]

#[doc = r" Error types."]
pub mod error {
    #[doc = r" Error from a `TryFrom` or `FromStr` implementation."]
    pub struct ConversionError(::std::borrow::Cow<'static, str>);
    impl ::std::error::Error for ConversionError {}
    impl ::std::fmt::Display for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Display::fmt(&self.0, f)
        }
    }
    impl ::std::fmt::Debug for ConversionError {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> Result<(), ::std::fmt::Error> {
            ::std::fmt::Debug::fmt(&self.0, f)
        }
    }
    impl From<&'static str> for ConversionError {
        fn from(value: &'static str) -> Self {
            Self(value.into())
        }
    }
    impl From<String> for ConversionError {
        fn from(value: String) -> Self {
            Self(value.into())
        }
    }
}
#[doc = "`AppearanceContent`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"string\","]
#[doc = "  \"enum\": ["]
#[doc = "    \"light\","]
#[doc = "    \"dark\""]
#[doc = "  ]"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum AppearanceContent {
    #[serde(rename = "light")]
    Light,
    #[serde(rename = "dark")]
    Dark,
}
impl ::std::convert::From<&Self> for AppearanceContent {
    fn from(value: &AppearanceContent) -> Self {
        value.clone()
    }
}
impl ::std::fmt::Display for AppearanceContent {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Light => f.write_str("light"),
            Self::Dark => f.write_str("dark"),
        }
    }
}
impl ::std::str::FromStr for AppearanceContent {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "light" => Ok(Self::Light),
            "dark" => Ok(Self::Dark),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for AppearanceContent {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for AppearanceContent {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for AppearanceContent {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
#[doc = "`FontStyleContent`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"string\","]
#[doc = "  \"enum\": ["]
#[doc = "    \"normal\","]
#[doc = "    \"italic\","]
#[doc = "    \"oblique\""]
#[doc = "  ]"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(
    :: serde :: Deserialize,
    :: serde :: Serialize,
    Clone,
    Copy,
    Debug,
    Eq,
    Hash,
    Ord,
    PartialEq,
    PartialOrd,
)]
pub enum FontStyleContent {
    #[serde(rename = "normal")]
    Normal,
    #[serde(rename = "italic")]
    Italic,
    #[serde(rename = "oblique")]
    Oblique,
}
impl ::std::convert::From<&Self> for FontStyleContent {
    fn from(value: &FontStyleContent) -> Self {
        value.clone()
    }
}
impl ::std::fmt::Display for FontStyleContent {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        match *self {
            Self::Normal => f.write_str("normal"),
            Self::Italic => f.write_str("italic"),
            Self::Oblique => f.write_str("oblique"),
        }
    }
}
impl ::std::str::FromStr for FontStyleContent {
    type Err = self::error::ConversionError;
    fn from_str(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        match value {
            "normal" => Ok(Self::Normal),
            "italic" => Ok(Self::Italic),
            "oblique" => Ok(Self::Oblique),
            _ => Err("invalid value".into()),
        }
    }
}
impl ::std::convert::TryFrom<&str> for FontStyleContent {
    type Error = self::error::ConversionError;
    fn try_from(value: &str) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<&::std::string::String> for FontStyleContent {
    type Error = self::error::ConversionError;
    fn try_from(
        value: &::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
impl ::std::convert::TryFrom<::std::string::String> for FontStyleContent {
    type Error = self::error::ConversionError;
    fn try_from(
        value: ::std::string::String,
    ) -> ::std::result::Result<Self, self::error::ConversionError> {
        value.parse()
    }
}
#[doc = "`HighlightStyleContent`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"properties\": {"]
#[doc = "    \"color\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"font_style\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"anyOf\": ["]
#[doc = "        {"]
#[doc = "          \"$ref\": \"#/definitions/FontStyleContent\""]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"type\": \"null\""]
#[doc = "        }"]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"font_weight\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"anyOf\": ["]
#[doc = "        {"]
#[doc = "          \"enum\": ["]
#[doc = "            100,"]
#[doc = "            200,"]
#[doc = "            300,"]
#[doc = "            400,"]
#[doc = "            500,"]
#[doc = "            600,"]
#[doc = "            700,"]
#[doc = "            800,"]
#[doc = "            900"]
#[doc = "          ]"]
#[doc = "        },"]
#[doc = "        {"]
#[doc = "          \"type\": \"null\""]
#[doc = "        }"]
#[doc = "      ]"]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct HighlightStyleContent {
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub color: ::std::option::Option<::std::string::String>,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub font_style: ::std::option::Option<FontStyleContent>,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub font_weight: ::std::option::Option<HighlightStyleContentFontWeight>,
}
impl ::std::convert::From<&HighlightStyleContent> for HighlightStyleContent {
    fn from(value: &HighlightStyleContent) -> Self {
        value.clone()
    }
}
impl ::std::default::Default for HighlightStyleContent {
    fn default() -> Self {
        Self {
            color: Default::default(),
            font_style: Default::default(),
            font_weight: Default::default(),
        }
    }
}
#[doc = "`HighlightStyleContentFontWeight`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"enum\": ["]
#[doc = "    100,"]
#[doc = "    200,"]
#[doc = "    300,"]
#[doc = "    400,"]
#[doc = "    500,"]
#[doc = "    600,"]
#[doc = "    700,"]
#[doc = "    800,"]
#[doc = "    900"]
#[doc = "  ]"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Serialize, Clone, Debug)]
#[serde(transparent)]
pub struct HighlightStyleContentFontWeight(f64);
impl ::std::ops::Deref for HighlightStyleContentFontWeight {
    type Target = f64;
    fn deref(&self) -> &f64 {
        &self.0
    }
}
impl ::std::convert::From<HighlightStyleContentFontWeight> for f64 {
    fn from(value: HighlightStyleContentFontWeight) -> Self {
        value.0
    }
}
impl ::std::convert::From<&HighlightStyleContentFontWeight> for HighlightStyleContentFontWeight {
    fn from(value: &HighlightStyleContentFontWeight) -> Self {
        value.clone()
    }
}
impl ::std::convert::TryFrom<f64> for HighlightStyleContentFontWeight {
    type Error = self::error::ConversionError;
    fn try_from(value: f64) -> ::std::result::Result<Self, self::error::ConversionError> {
        if ![
            100_f64, 200_f64, 300_f64, 400_f64, 500_f64, 600_f64, 700_f64, 800_f64, 900_f64,
        ]
        .contains(&value)
        {
            Err("invalid value".into())
        } else {
            Ok(Self(value))
        }
    }
}
impl<'de> ::serde::Deserialize<'de> for HighlightStyleContentFontWeight {
    fn deserialize<D>(deserializer: D) -> ::std::result::Result<Self, D::Error>
    where
        D: ::serde::Deserializer<'de>,
    {
        Self::try_from(<f64>::deserialize(deserializer)?)
            .map_err(|e| <D::Error as ::serde::de::Error>::custom(e.to_string()))
    }
}
#[doc = "`PlayerColorContent`"]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"properties\": {"]
#[doc = "    \"background\": {"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"cursor\": {"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"selection\": {"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct PlayerColorContent {
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub background: ::std::option::Option<::std::string::String>,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub cursor: ::std::option::Option<::std::string::String>,
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub selection: ::std::option::Option<::std::string::String>,
}
impl ::std::convert::From<&PlayerColorContent> for PlayerColorContent {
    fn from(value: &PlayerColorContent) -> Self {
        value.clone()
    }
}
impl ::std::default::Default for PlayerColorContent {
    fn default() -> Self {
        Self {
            background: Default::default(),
            cursor: Default::default(),
            selection: Default::default(),
        }
    }
}
#[doc = "The content of a serialized theme."]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"description\": \"The content of a serialized theme.\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"appearance\","]
#[doc = "    \"name\","]
#[doc = "    \"style\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"appearance\": {"]
#[doc = "      \"$ref\": \"#/definitions/AppearanceContent\""]
#[doc = "    },"]
#[doc = "    \"name\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"style\": {"]
#[doc = "      \"$ref\": \"#/definitions/ThemeStyleContent\""]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct ThemeContent {
    pub appearance: AppearanceContent,
    pub name: ::std::string::String,
    pub style: ThemeStyleContent,
}
impl ::std::convert::From<&ThemeContent> for ThemeContent {
    fn from(value: &ThemeContent) -> Self {
        value.clone()
    }
}
#[doc = "The content of a serialized theme family."]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"title\": \"ThemeFamilyContent\","]
#[doc = "  \"description\": \"The content of a serialized theme family.\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"required\": ["]
#[doc = "    \"author\","]
#[doc = "    \"name\","]
#[doc = "    \"themes\""]
#[doc = "  ],"]
#[doc = "  \"properties\": {"]
#[doc = "    \"author\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"name\": {"]
#[doc = "      \"type\": \"string\""]
#[doc = "    },"]
#[doc = "    \"themes\": {"]
#[doc = "      \"type\": \"array\","]
#[doc = "      \"items\": {"]
#[doc = "        \"$ref\": \"#/definitions/ThemeContent\""]
#[doc = "      }"]
#[doc = "    }"]
#[doc = "  },"]
#[doc = "  \"$comment\": \"Downloaded from https://zed.dev/schema/themes/v0.1.0.json\""]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct ThemeFamilyContent {
    pub author: ::std::string::String,
    pub name: ::std::string::String,
    pub themes: ::std::vec::Vec<ThemeContent>,
}
impl ::std::convert::From<&ThemeFamilyContent> for ThemeFamilyContent {
    fn from(value: &ThemeFamilyContent) -> Self {
        value.clone()
    }
}
#[doc = "The content of a serialized theme."]
#[doc = r""]
#[doc = r" <details><summary>JSON schema</summary>"]
#[doc = r""]
#[doc = r" ```json"]
#[doc = "{"]
#[doc = "  \"description\": \"The content of a serialized theme.\","]
#[doc = "  \"type\": \"object\","]
#[doc = "  \"properties\": {"]
#[doc = "    \"background\": {"]
#[doc = "      \"description\": \"Background Color. Used for the app background and blank panels or windows.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"border\": {"]
#[doc = "      \"description\": \"Border color. Used for most borders, is usually a high contrast color.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"border.disabled\": {"]
#[doc = "      \"description\": \"Border color. Used for disabled elements, like a disabled input or button.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"border.focused\": {"]
#[doc = "      \"description\": \"Border color. Used for focused elements, like keyboard focused list item.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"border.selected\": {"]
#[doc = "      \"description\": \"Border color. Used for selected elements, like an active search filter or selected checkbox.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"border.transparent\": {"]
#[doc = "      \"description\": \"Border color. Used for transparent borders. Used for placeholder borders when an element gains a border on state change.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"border.variant\": {"]
#[doc = "      \"description\": \"Border color. Used for deemphasized borders, like a visual divider between two sections\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"conflict\": {"]
#[doc = "      \"description\": \"Indicates some kind of conflict, like a file changed on disk while it was open, or merge conflicts in a Git repository.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"conflict.background\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"conflict.border\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"created\": {"]
#[doc = "      \"description\": \"Indicates something new, like a new file added to a Git repository.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"created.background\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"created.border\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"deleted\": {"]
#[doc = "      \"description\": \"Indicates that something no longer exists, like a deleted file.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"deleted.background\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"deleted.border\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"drop_target.background\": {"]
#[doc = "      \"description\": \"Background Color. Used for the area that shows where a dragged element will be dropped.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"editor.active_line.background\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"editor.active_line_number\": {"]
#[doc = "      \"description\": \"Text Color. Used for the text of the line number in the editor gutter when the line is highlighted.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"editor.active_wrap_guide\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"editor.background\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"editor.document_highlight.read_background\": {"]
#[doc = "      \"description\": \"Read-access of a symbol, like reading a variable.\\n\\nA document highlight is a range inside a text document which deserves special attention. Usually a document highlight is visualized by changing the background color of its range.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"editor.document_highlight.write_background\": {"]
#[doc = "      \"description\": \"Read-access of a symbol, like reading a variable.\\n\\nA document highlight is a range inside a text document which deserves special attention. Usually a document highlight is visualized by changing the background color of its range.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"editor.foreground\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"editor.gutter.background\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"editor.highlighted_line.background\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"editor.invisible\": {"]
#[doc = "      \"description\": \"Text Color. Used to mark invisible characters in the editor.\\n\\nExample: spaces, tabs, carriage returns, etc.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"editor.line_number\": {"]
#[doc = "      \"description\": \"Text Color. Used for the text of the line number in the editor gutter.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"editor.subheader.background\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"editor.wrap_guide\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"element.active\": {"]
#[doc = "      \"description\": \"Background Color. Used for the active state of an element that should have a different background than the surface it's on.\\n\\nActive states are triggered by the mouse button being pressed down on an element, or the Return button or other activator being pressd.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"element.background\": {"]
#[doc = "      \"description\": \"Background Color. Used for the background of an element that should have a different background than the surface it's on.\\n\\nElements might include: Buttons, Inputs, Checkboxes, Radio Buttons...\\n\\nFor an element that should have the same background as the surface it's on, use `ghost_element_background`.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"element.disabled\": {"]
#[doc = "      \"description\": \"Background Color. Used for the disabled state of an element that should have a different background than the surface it's on.\\n\\nDisabled states are shown when a user cannot interact with an element, like a disabled button or input.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"element.hover\": {"]
#[doc = "      \"description\": \"Background Color. Used for the hover state of an element that should have a different background than the surface it's on.\\n\\nHover states are triggered by the mouse entering an element, or a finger touching an element on a touch screen.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"element.selected\": {"]
#[doc = "      \"description\": \"Background Color. Used for the selected state of an element that should have a different background than the surface it's on.\\n\\nSelected states are triggered by the element being selected (or \\\"activated\\\") by the user.\\n\\nThis could include a selected checkbox, a toggleable button that is toggled on, etc.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"elevated_surface.background\": {"]
#[doc = "      \"description\": \"Border color. Used for elevated surfaces, like a context menu, popup, or dialog.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"error\": {"]
#[doc = "      \"description\": \"Indicates a system error, a failed operation or a diagnostic error.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"error.background\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"error.border\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"ghost_element.active\": {"]
#[doc = "      \"description\": \"Background Color. Used for the active state of a ghost element that should have the same background as the surface it's on.\\n\\nActive states are triggered by the mouse button being pressed down on an element, or the Return button or other activator being pressd.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"ghost_element.background\": {"]
#[doc = "      \"description\": \"Used for the background of a ghost element that should have the same background as the surface it's on.\\n\\nElements might include: Buttons, Inputs, Checkboxes, Radio Buttons...\\n\\nFor an element that should have a different background than the surface it's on, use `element_background`.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"ghost_element.disabled\": {"]
#[doc = "      \"description\": \"Background Color. Used for the disabled state of a ghost element that should have the same background as the surface it's on.\\n\\nDisabled states are shown when a user cannot interact with an element, like a disabled button or input.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"ghost_element.hover\": {"]
#[doc = "      \"description\": \"Background Color. Used for the hover state of a ghost element that should have the same background as the surface it's on.\\n\\nHover states are triggered by the mouse entering an element, or a finger touching an element on a touch screen.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"ghost_element.selected\": {"]
#[doc = "      \"description\": \"Background Color. Used for the selected state of a ghost element that should have the same background as the surface it's on.\\n\\nSelected states are triggered by the element being selected (or \\\"activated\\\") by the user.\\n\\nThis could include a selected checkbox, a toggleable button that is toggled on, etc.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"hidden\": {"]
#[doc = "      \"description\": \"Represents a hidden status, such as a file being hidden in a file tree.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"hidden.background\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"hidden.border\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"hint\": {"]
#[doc = "      \"description\": \"Indicates a hint or some kind of additional information.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"hint.background\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"hint.border\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"icon\": {"]
#[doc = "      \"description\": \"Fill Color. Used for the default fill color of an icon.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"icon.accent\": {"]
#[doc = "      \"description\": \"Fill Color. Used for the accent fill color of an icon.\\n\\nThis might be used to show when a toggleable icon button is selected.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"icon.disabled\": {"]
#[doc = "      \"description\": \"Fill Color. Used for the disabled fill color of an icon.\\n\\nDisabled states are shown when a user cannot interact with an element, like a icon button.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"icon.muted\": {"]
#[doc = "      \"description\": \"Fill Color. Used for the muted or deemphasized fill color of an icon.\\n\\nThis might be used to show an icon in an inactive pane, or to demphasize a series of icons to give them less visual weight.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"icon.placeholder\": {"]
#[doc = "      \"description\": \"Fill Color. Used for the placeholder fill color of an icon.\\n\\nThis might be used to show an icon in an input that disappears when the user enters text.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"ignored\": {"]
#[doc = "      \"description\": \"Indicates that something is deliberately ignored, such as a file or operation ignored by Git.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"ignored.background\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"ignored.border\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"info\": {"]
#[doc = "      \"description\": \"Represents informational status updates or messages.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"info.background\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"info.border\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"link_text.hover\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"modified\": {"]
#[doc = "      \"description\": \"Indicates a changed or altered status, like a file that has been edited.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"modified.background\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"modified.border\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"pane.focused_border\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"panel.background\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"panel.focused_border\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"players\": {"]
#[doc = "      \"default\": [],"]
#[doc = "      \"type\": \"array\","]
#[doc = "      \"items\": {"]
#[doc = "        \"$ref\": \"#/definitions/PlayerColorContent\""]
#[doc = "      }"]
#[doc = "    },"]
#[doc = "    \"predictive\": {"]
#[doc = "      \"description\": \"Indicates something that is predicted, like automatic code completion, or generated code.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"predictive.background\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"predictive.border\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"renamed\": {"]
#[doc = "      \"description\": \"Represents a renamed status, such as a file that has been renamed.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"renamed.background\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"renamed.border\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"scrollbar.thumb.border\": {"]
#[doc = "      \"description\": \"The border color of the scrollbar thumb.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"scrollbar.thumb.hover_background\": {"]
#[doc = "      \"description\": \"The color of the scrollbar thumb when hovered over.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"scrollbar.track.background\": {"]
#[doc = "      \"description\": \"The background color of the scrollbar track.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"scrollbar.track.border\": {"]
#[doc = "      \"description\": \"The border color of the scrollbar track.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"scrollbar_thumb.background\": {"]
#[doc = "      \"description\": \"The color of the scrollbar thumb.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"search.match_background\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"status_bar.background\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"success\": {"]
#[doc = "      \"description\": \"Indicates a successful operation or task completion.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"success.background\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"success.border\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"surface.background\": {"]
#[doc = "      \"description\": \"Background Color. Used for grounded surfaces like a panel or tab.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"syntax\": {"]
#[doc = "      \"description\": \"The styles for syntax nodes.\","]
#[doc = "      \"default\": {},"]
#[doc = "      \"type\": \"object\","]
#[doc = "      \"additionalProperties\": {"]
#[doc = "        \"$ref\": \"#/definitions/HighlightStyleContent\""]
#[doc = "      }"]
#[doc = "    },"]
#[doc = "    \"tab.active_background\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"tab.inactive_background\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"tab_bar.background\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"terminal.ansi.black\": {"]
#[doc = "      \"description\": \"Black ANSI terminal color.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"terminal.ansi.blue\": {"]
#[doc = "      \"description\": \"Blue ANSI terminal color.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"terminal.ansi.bright_black\": {"]
#[doc = "      \"description\": \"Bright black ANSI terminal color.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"terminal.ansi.bright_blue\": {"]
#[doc = "      \"description\": \"Bright blue ANSI terminal color.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"terminal.ansi.bright_cyan\": {"]
#[doc = "      \"description\": \"Bright cyan ANSI terminal color.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"terminal.ansi.bright_green\": {"]
#[doc = "      \"description\": \"Bright green ANSI terminal color.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"terminal.ansi.bright_magenta\": {"]
#[doc = "      \"description\": \"Bright magenta ANSI terminal color.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"terminal.ansi.bright_red\": {"]
#[doc = "      \"description\": \"Bright red ANSI terminal color.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"terminal.ansi.bright_white\": {"]
#[doc = "      \"description\": \"Bright white ANSI terminal color.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"terminal.ansi.bright_yellow\": {"]
#[doc = "      \"description\": \"Bright yellow ANSI terminal color.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"terminal.ansi.cyan\": {"]
#[doc = "      \"description\": \"Cyan ANSI terminal color.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"terminal.ansi.dim_black\": {"]
#[doc = "      \"description\": \"Dim black ANSI terminal color.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"terminal.ansi.dim_blue\": {"]
#[doc = "      \"description\": \"Dim blue ANSI terminal color.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"terminal.ansi.dim_cyan\": {"]
#[doc = "      \"description\": \"Dim cyan ANSI terminal color.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"terminal.ansi.dim_green\": {"]
#[doc = "      \"description\": \"Dim green ANSI terminal color.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"terminal.ansi.dim_magenta\": {"]
#[doc = "      \"description\": \"Dim magenta ANSI terminal color.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"terminal.ansi.dim_red\": {"]
#[doc = "      \"description\": \"Dim red ANSI terminal color.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"terminal.ansi.dim_white\": {"]
#[doc = "      \"description\": \"Dim white ANSI terminal color.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"terminal.ansi.dim_yellow\": {"]
#[doc = "      \"description\": \"Dim yellow ANSI terminal color.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"terminal.ansi.green\": {"]
#[doc = "      \"description\": \"Green ANSI terminal color.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"terminal.ansi.magenta\": {"]
#[doc = "      \"description\": \"Magenta ANSI terminal color.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"terminal.ansi.red\": {"]
#[doc = "      \"description\": \"Red ANSI terminal color.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"terminal.ansi.white\": {"]
#[doc = "      \"description\": \"White ANSI terminal color.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"terminal.ansi.yellow\": {"]
#[doc = "      \"description\": \"Yellow ANSI terminal color.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"terminal.background\": {"]
#[doc = "      \"description\": \"Terminal background color.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"terminal.bright_foreground\": {"]
#[doc = "      \"description\": \"Bright terminal foreground color.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"terminal.dim_foreground\": {"]
#[doc = "      \"description\": \"Dim terminal foreground color.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"terminal.foreground\": {"]
#[doc = "      \"description\": \"Terminal foreground color.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"text\": {"]
#[doc = "      \"description\": \"Text Color. Default text color used for most text.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"text.accent\": {"]
#[doc = "      \"description\": \"Text Color. Color used for emphasis or highlighting certain text, like an active filter or a matched character in a search.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"text.disabled\": {"]
#[doc = "      \"description\": \"Text Color. Color used for text denoting disabled elements. Typically, the color is faded or grayed out to emphasize the disabled state.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"text.muted\": {"]
#[doc = "      \"description\": \"Text Color. Color of muted or deemphasized text. It is a subdued version of the standard text color.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"text.placeholder\": {"]
#[doc = "      \"description\": \"Text Color. Color of the placeholder text typically shown in input fields to guide the user to enter valid data.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"title_bar.background\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"toolbar.background\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"unreachable\": {"]
#[doc = "      \"description\": \"Indicates some kind of unreachable status, like a block of code that can never be reached.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"unreachable.background\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"unreachable.border\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"warning\": {"]
#[doc = "      \"description\": \"Represents a warning status, like an operation that is about to fail.\","]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"warning.background\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    },"]
#[doc = "    \"warning.border\": {"]
#[doc = "      \"default\": null,"]
#[doc = "      \"type\": ["]
#[doc = "        \"string\","]
#[doc = "        \"null\""]
#[doc = "      ]"]
#[doc = "    }"]
#[doc = "  }"]
#[doc = "}"]
#[doc = r" ```"]
#[doc = r" </details>"]
#[derive(:: serde :: Deserialize, :: serde :: Serialize, Clone, Debug)]
pub struct ThemeStyleContent {
    #[doc = "Background Color. Used for the app background and blank panels or windows."]
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub background: ::std::option::Option<::std::string::String>,
    #[doc = "Border color. Used for most borders, is usually a high contrast color."]
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub border: ::std::option::Option<::std::string::String>,
    #[doc = "Border color. Used for disabled elements, like a disabled input or button."]
    #[serde(
        rename = "border.disabled",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub border_disabled: ::std::option::Option<::std::string::String>,
    #[doc = "Border color. Used for focused elements, like keyboard focused list item."]
    #[serde(
        rename = "border.focused",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub border_focused: ::std::option::Option<::std::string::String>,
    #[doc = "Border color. Used for selected elements, like an active search filter or selected checkbox."]
    #[serde(
        rename = "border.selected",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub border_selected: ::std::option::Option<::std::string::String>,
    #[doc = "Border color. Used for transparent borders. Used for placeholder borders when an element gains a border on state change."]
    #[serde(
        rename = "border.transparent",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub border_transparent: ::std::option::Option<::std::string::String>,
    #[doc = "Border color. Used for deemphasized borders, like a visual divider between two sections"]
    #[serde(
        rename = "border.variant",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub border_variant: ::std::option::Option<::std::string::String>,
    #[doc = "Indicates some kind of conflict, like a file changed on disk while it was open, or merge conflicts in a Git repository."]
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub conflict: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "conflict.background",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub conflict_background: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "conflict.border",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub conflict_border: ::std::option::Option<::std::string::String>,
    #[doc = "Indicates something new, like a new file added to a Git repository."]
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub created: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "created.background",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub created_background: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "created.border",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub created_border: ::std::option::Option<::std::string::String>,
    #[doc = "Indicates that something no longer exists, like a deleted file."]
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub deleted: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "deleted.background",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub deleted_background: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "deleted.border",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub deleted_border: ::std::option::Option<::std::string::String>,
    #[doc = "Background Color. Used for the area that shows where a dragged element will be dropped."]
    #[serde(
        rename = "drop_target.background",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub drop_target_background: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "editor.active_line.background",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub editor_active_line_background: ::std::option::Option<::std::string::String>,
    #[doc = "Text Color. Used for the text of the line number in the editor gutter when the line is highlighted."]
    #[serde(
        rename = "editor.active_line_number",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub editor_active_line_number: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "editor.active_wrap_guide",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub editor_active_wrap_guide: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "editor.background",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub editor_background: ::std::option::Option<::std::string::String>,
    #[doc = "Read-access of a symbol, like reading a variable.\n\nA document highlight is a range inside a text document which deserves special attention. Usually a document highlight is visualized by changing the background color of its range."]
    #[serde(
        rename = "editor.document_highlight.read_background",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub editor_document_highlight_read_background: ::std::option::Option<::std::string::String>,
    #[doc = "Read-access of a symbol, like reading a variable.\n\nA document highlight is a range inside a text document which deserves special attention. Usually a document highlight is visualized by changing the background color of its range."]
    #[serde(
        rename = "editor.document_highlight.write_background",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub editor_document_highlight_write_background: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "editor.foreground",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub editor_foreground: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "editor.gutter.background",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub editor_gutter_background: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "editor.highlighted_line.background",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub editor_highlighted_line_background: ::std::option::Option<::std::string::String>,
    #[doc = "Text Color. Used to mark invisible characters in the editor.\n\nExample: spaces, tabs, carriage returns, etc."]
    #[serde(
        rename = "editor.invisible",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub editor_invisible: ::std::option::Option<::std::string::String>,
    #[doc = "Text Color. Used for the text of the line number in the editor gutter."]
    #[serde(
        rename = "editor.line_number",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub editor_line_number: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "editor.subheader.background",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub editor_subheader_background: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "editor.wrap_guide",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub editor_wrap_guide: ::std::option::Option<::std::string::String>,
    #[doc = "Background Color. Used for the active state of an element that should have a different background than the surface it's on.\n\nActive states are triggered by the mouse button being pressed down on an element, or the Return button or other activator being pressd."]
    #[serde(
        rename = "element.active",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub element_active: ::std::option::Option<::std::string::String>,
    #[doc = "Background Color. Used for the background of an element that should have a different background than the surface it's on.\n\nElements might include: Buttons, Inputs, Checkboxes, Radio Buttons...\n\nFor an element that should have the same background as the surface it's on, use `ghost_element_background`."]
    #[serde(
        rename = "element.background",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub element_background: ::std::option::Option<::std::string::String>,
    #[doc = "Background Color. Used for the disabled state of an element that should have a different background than the surface it's on.\n\nDisabled states are shown when a user cannot interact with an element, like a disabled button or input."]
    #[serde(
        rename = "element.disabled",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub element_disabled: ::std::option::Option<::std::string::String>,
    #[doc = "Background Color. Used for the hover state of an element that should have a different background than the surface it's on.\n\nHover states are triggered by the mouse entering an element, or a finger touching an element on a touch screen."]
    #[serde(
        rename = "element.hover",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub element_hover: ::std::option::Option<::std::string::String>,
    #[doc = "Background Color. Used for the selected state of an element that should have a different background than the surface it's on.\n\nSelected states are triggered by the element being selected (or \"activated\") by the user.\n\nThis could include a selected checkbox, a toggleable button that is toggled on, etc."]
    #[serde(
        rename = "element.selected",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub element_selected: ::std::option::Option<::std::string::String>,
    #[doc = "Border color. Used for elevated surfaces, like a context menu, popup, or dialog."]
    #[serde(
        rename = "elevated_surface.background",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub elevated_surface_background: ::std::option::Option<::std::string::String>,
    #[doc = "Indicates a system error, a failed operation or a diagnostic error."]
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub error: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "error.background",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub error_background: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "error.border",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub error_border: ::std::option::Option<::std::string::String>,
    #[doc = "Background Color. Used for the active state of a ghost element that should have the same background as the surface it's on.\n\nActive states are triggered by the mouse button being pressed down on an element, or the Return button or other activator being pressd."]
    #[serde(
        rename = "ghost_element.active",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub ghost_element_active: ::std::option::Option<::std::string::String>,
    #[doc = "Used for the background of a ghost element that should have the same background as the surface it's on.\n\nElements might include: Buttons, Inputs, Checkboxes, Radio Buttons...\n\nFor an element that should have a different background than the surface it's on, use `element_background`."]
    #[serde(
        rename = "ghost_element.background",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub ghost_element_background: ::std::option::Option<::std::string::String>,
    #[doc = "Background Color. Used for the disabled state of a ghost element that should have the same background as the surface it's on.\n\nDisabled states are shown when a user cannot interact with an element, like a disabled button or input."]
    #[serde(
        rename = "ghost_element.disabled",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub ghost_element_disabled: ::std::option::Option<::std::string::String>,
    #[doc = "Background Color. Used for the hover state of a ghost element that should have the same background as the surface it's on.\n\nHover states are triggered by the mouse entering an element, or a finger touching an element on a touch screen."]
    #[serde(
        rename = "ghost_element.hover",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub ghost_element_hover: ::std::option::Option<::std::string::String>,
    #[doc = "Background Color. Used for the selected state of a ghost element that should have the same background as the surface it's on.\n\nSelected states are triggered by the element being selected (or \"activated\") by the user.\n\nThis could include a selected checkbox, a toggleable button that is toggled on, etc."]
    #[serde(
        rename = "ghost_element.selected",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub ghost_element_selected: ::std::option::Option<::std::string::String>,
    #[doc = "Represents a hidden status, such as a file being hidden in a file tree."]
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub hidden: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "hidden.background",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub hidden_background: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "hidden.border",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub hidden_border: ::std::option::Option<::std::string::String>,
    #[doc = "Indicates a hint or some kind of additional information."]
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub hint: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "hint.background",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub hint_background: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "hint.border",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub hint_border: ::std::option::Option<::std::string::String>,
    #[doc = "Fill Color. Used for the default fill color of an icon."]
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub icon: ::std::option::Option<::std::string::String>,
    #[doc = "Fill Color. Used for the accent fill color of an icon.\n\nThis might be used to show when a toggleable icon button is selected."]
    #[serde(
        rename = "icon.accent",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub icon_accent: ::std::option::Option<::std::string::String>,
    #[doc = "Fill Color. Used for the disabled fill color of an icon.\n\nDisabled states are shown when a user cannot interact with an element, like a icon button."]
    #[serde(
        rename = "icon.disabled",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub icon_disabled: ::std::option::Option<::std::string::String>,
    #[doc = "Fill Color. Used for the muted or deemphasized fill color of an icon.\n\nThis might be used to show an icon in an inactive pane, or to demphasize a series of icons to give them less visual weight."]
    #[serde(
        rename = "icon.muted",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub icon_muted: ::std::option::Option<::std::string::String>,
    #[doc = "Fill Color. Used for the placeholder fill color of an icon.\n\nThis might be used to show an icon in an input that disappears when the user enters text."]
    #[serde(
        rename = "icon.placeholder",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub icon_placeholder: ::std::option::Option<::std::string::String>,
    #[doc = "Indicates that something is deliberately ignored, such as a file or operation ignored by Git."]
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub ignored: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "ignored.background",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub ignored_background: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "ignored.border",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub ignored_border: ::std::option::Option<::std::string::String>,
    #[doc = "Represents informational status updates or messages."]
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub info: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "info.background",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub info_background: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "info.border",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub info_border: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "link_text.hover",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub link_text_hover: ::std::option::Option<::std::string::String>,
    #[doc = "Indicates a changed or altered status, like a file that has been edited."]
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub modified: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "modified.background",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub modified_background: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "modified.border",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub modified_border: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "pane.focused_border",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub pane_focused_border: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "panel.background",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub panel_background: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "panel.focused_border",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub panel_focused_border: ::std::option::Option<::std::string::String>,
    #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
    pub players: ::std::vec::Vec<PlayerColorContent>,
    #[doc = "Indicates something that is predicted, like automatic code completion, or generated code."]
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub predictive: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "predictive.background",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub predictive_background: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "predictive.border",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub predictive_border: ::std::option::Option<::std::string::String>,
    #[doc = "Represents a renamed status, such as a file that has been renamed."]
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub renamed: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "renamed.background",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub renamed_background: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "renamed.border",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub renamed_border: ::std::option::Option<::std::string::String>,
    #[doc = "The color of the scrollbar thumb."]
    #[serde(
        rename = "scrollbar_thumb.background",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub scrollbar_thumb_background: ::std::option::Option<::std::string::String>,
    #[doc = "The border color of the scrollbar thumb."]
    #[serde(
        rename = "scrollbar.thumb.border",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub scrollbar_thumb_border: ::std::option::Option<::std::string::String>,
    #[doc = "The color of the scrollbar thumb when hovered over."]
    #[serde(
        rename = "scrollbar.thumb.hover_background",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub scrollbar_thumb_hover_background: ::std::option::Option<::std::string::String>,
    #[doc = "The background color of the scrollbar track."]
    #[serde(
        rename = "scrollbar.track.background",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub scrollbar_track_background: ::std::option::Option<::std::string::String>,
    #[doc = "The border color of the scrollbar track."]
    #[serde(
        rename = "scrollbar.track.border",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub scrollbar_track_border: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "search.match_background",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub search_match_background: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "status_bar.background",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub status_bar_background: ::std::option::Option<::std::string::String>,
    #[doc = "Indicates a successful operation or task completion."]
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub success: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "success.background",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub success_background: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "success.border",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub success_border: ::std::option::Option<::std::string::String>,
    #[doc = "Background Color. Used for grounded surfaces like a panel or tab."]
    #[serde(
        rename = "surface.background",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub surface_background: ::std::option::Option<::std::string::String>,
    #[doc = "The styles for syntax nodes."]
    #[serde(
        default,
        skip_serializing_if = ":: std :: collections :: HashMap::is_empty"
    )]
    pub syntax: ::std::collections::HashMap<::std::string::String, HighlightStyleContent>,
    #[serde(
        rename = "tab.active_background",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub tab_active_background: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "tab_bar.background",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub tab_bar_background: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "tab.inactive_background",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub tab_inactive_background: ::std::option::Option<::std::string::String>,
    #[doc = "Black ANSI terminal color."]
    #[serde(
        rename = "terminal.ansi.black",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub terminal_ansi_black: ::std::option::Option<::std::string::String>,
    #[doc = "Blue ANSI terminal color."]
    #[serde(
        rename = "terminal.ansi.blue",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub terminal_ansi_blue: ::std::option::Option<::std::string::String>,
    #[doc = "Bright black ANSI terminal color."]
    #[serde(
        rename = "terminal.ansi.bright_black",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub terminal_ansi_bright_black: ::std::option::Option<::std::string::String>,
    #[doc = "Bright blue ANSI terminal color."]
    #[serde(
        rename = "terminal.ansi.bright_blue",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub terminal_ansi_bright_blue: ::std::option::Option<::std::string::String>,
    #[doc = "Bright cyan ANSI terminal color."]
    #[serde(
        rename = "terminal.ansi.bright_cyan",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub terminal_ansi_bright_cyan: ::std::option::Option<::std::string::String>,
    #[doc = "Bright green ANSI terminal color."]
    #[serde(
        rename = "terminal.ansi.bright_green",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub terminal_ansi_bright_green: ::std::option::Option<::std::string::String>,
    #[doc = "Bright magenta ANSI terminal color."]
    #[serde(
        rename = "terminal.ansi.bright_magenta",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub terminal_ansi_bright_magenta: ::std::option::Option<::std::string::String>,
    #[doc = "Bright red ANSI terminal color."]
    #[serde(
        rename = "terminal.ansi.bright_red",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub terminal_ansi_bright_red: ::std::option::Option<::std::string::String>,
    #[doc = "Bright white ANSI terminal color."]
    #[serde(
        rename = "terminal.ansi.bright_white",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub terminal_ansi_bright_white: ::std::option::Option<::std::string::String>,
    #[doc = "Bright yellow ANSI terminal color."]
    #[serde(
        rename = "terminal.ansi.bright_yellow",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub terminal_ansi_bright_yellow: ::std::option::Option<::std::string::String>,
    #[doc = "Cyan ANSI terminal color."]
    #[serde(
        rename = "terminal.ansi.cyan",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub terminal_ansi_cyan: ::std::option::Option<::std::string::String>,
    #[doc = "Dim black ANSI terminal color."]
    #[serde(
        rename = "terminal.ansi.dim_black",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub terminal_ansi_dim_black: ::std::option::Option<::std::string::String>,
    #[doc = "Dim blue ANSI terminal color."]
    #[serde(
        rename = "terminal.ansi.dim_blue",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub terminal_ansi_dim_blue: ::std::option::Option<::std::string::String>,
    #[doc = "Dim cyan ANSI terminal color."]
    #[serde(
        rename = "terminal.ansi.dim_cyan",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub terminal_ansi_dim_cyan: ::std::option::Option<::std::string::String>,
    #[doc = "Dim green ANSI terminal color."]
    #[serde(
        rename = "terminal.ansi.dim_green",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub terminal_ansi_dim_green: ::std::option::Option<::std::string::String>,
    #[doc = "Dim magenta ANSI terminal color."]
    #[serde(
        rename = "terminal.ansi.dim_magenta",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub terminal_ansi_dim_magenta: ::std::option::Option<::std::string::String>,
    #[doc = "Dim red ANSI terminal color."]
    #[serde(
        rename = "terminal.ansi.dim_red",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub terminal_ansi_dim_red: ::std::option::Option<::std::string::String>,
    #[doc = "Dim white ANSI terminal color."]
    #[serde(
        rename = "terminal.ansi.dim_white",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub terminal_ansi_dim_white: ::std::option::Option<::std::string::String>,
    #[doc = "Dim yellow ANSI terminal color."]
    #[serde(
        rename = "terminal.ansi.dim_yellow",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub terminal_ansi_dim_yellow: ::std::option::Option<::std::string::String>,
    #[doc = "Green ANSI terminal color."]
    #[serde(
        rename = "terminal.ansi.green",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub terminal_ansi_green: ::std::option::Option<::std::string::String>,
    #[doc = "Magenta ANSI terminal color."]
    #[serde(
        rename = "terminal.ansi.magenta",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub terminal_ansi_magenta: ::std::option::Option<::std::string::String>,
    #[doc = "Red ANSI terminal color."]
    #[serde(
        rename = "terminal.ansi.red",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub terminal_ansi_red: ::std::option::Option<::std::string::String>,
    #[doc = "White ANSI terminal color."]
    #[serde(
        rename = "terminal.ansi.white",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub terminal_ansi_white: ::std::option::Option<::std::string::String>,
    #[doc = "Yellow ANSI terminal color."]
    #[serde(
        rename = "terminal.ansi.yellow",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub terminal_ansi_yellow: ::std::option::Option<::std::string::String>,
    #[doc = "Terminal background color."]
    #[serde(
        rename = "terminal.background",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub terminal_background: ::std::option::Option<::std::string::String>,
    #[doc = "Bright terminal foreground color."]
    #[serde(
        rename = "terminal.bright_foreground",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub terminal_bright_foreground: ::std::option::Option<::std::string::String>,
    #[doc = "Dim terminal foreground color."]
    #[serde(
        rename = "terminal.dim_foreground",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub terminal_dim_foreground: ::std::option::Option<::std::string::String>,
    #[doc = "Terminal foreground color."]
    #[serde(
        rename = "terminal.foreground",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub terminal_foreground: ::std::option::Option<::std::string::String>,
    #[doc = "Text Color. Default text color used for most text."]
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub text: ::std::option::Option<::std::string::String>,
    #[doc = "Text Color. Color used for emphasis or highlighting certain text, like an active filter or a matched character in a search."]
    #[serde(
        rename = "text.accent",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub text_accent: ::std::option::Option<::std::string::String>,
    #[doc = "Text Color. Color used for text denoting disabled elements. Typically, the color is faded or grayed out to emphasize the disabled state."]
    #[serde(
        rename = "text.disabled",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub text_disabled: ::std::option::Option<::std::string::String>,
    #[doc = "Text Color. Color of muted or deemphasized text. It is a subdued version of the standard text color."]
    #[serde(
        rename = "text.muted",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub text_muted: ::std::option::Option<::std::string::String>,
    #[doc = "Text Color. Color of the placeholder text typically shown in input fields to guide the user to enter valid data."]
    #[serde(
        rename = "text.placeholder",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub text_placeholder: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "title_bar.background",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub title_bar_background: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "toolbar.background",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub toolbar_background: ::std::option::Option<::std::string::String>,
    #[doc = "Indicates some kind of unreachable status, like a block of code that can never be reached."]
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub unreachable: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "unreachable.background",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub unreachable_background: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "unreachable.border",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub unreachable_border: ::std::option::Option<::std::string::String>,
    #[doc = "Represents a warning status, like an operation that is about to fail."]
    #[serde(default, skip_serializing_if = "::std::option::Option::is_none")]
    pub warning: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "warning.background",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub warning_background: ::std::option::Option<::std::string::String>,
    #[serde(
        rename = "warning.border",
        default,
        skip_serializing_if = "::std::option::Option::is_none"
    )]
    pub warning_border: ::std::option::Option<::std::string::String>,
}
impl ::std::convert::From<&ThemeStyleContent> for ThemeStyleContent {
    fn from(value: &ThemeStyleContent) -> Self {
        value.clone()
    }
}
impl ::std::default::Default for ThemeStyleContent {
    fn default() -> Self {
        Self {
            background: Default::default(),
            border: Default::default(),
            border_disabled: Default::default(),
            border_focused: Default::default(),
            border_selected: Default::default(),
            border_transparent: Default::default(),
            border_variant: Default::default(),
            conflict: Default::default(),
            conflict_background: Default::default(),
            conflict_border: Default::default(),
            created: Default::default(),
            created_background: Default::default(),
            created_border: Default::default(),
            deleted: Default::default(),
            deleted_background: Default::default(),
            deleted_border: Default::default(),
            drop_target_background: Default::default(),
            editor_active_line_background: Default::default(),
            editor_active_line_number: Default::default(),
            editor_active_wrap_guide: Default::default(),
            editor_background: Default::default(),
            editor_document_highlight_read_background: Default::default(),
            editor_document_highlight_write_background: Default::default(),
            editor_foreground: Default::default(),
            editor_gutter_background: Default::default(),
            editor_highlighted_line_background: Default::default(),
            editor_invisible: Default::default(),
            editor_line_number: Default::default(),
            editor_subheader_background: Default::default(),
            editor_wrap_guide: Default::default(),
            element_active: Default::default(),
            element_background: Default::default(),
            element_disabled: Default::default(),
            element_hover: Default::default(),
            element_selected: Default::default(),
            elevated_surface_background: Default::default(),
            error: Default::default(),
            error_background: Default::default(),
            error_border: Default::default(),
            ghost_element_active: Default::default(),
            ghost_element_background: Default::default(),
            ghost_element_disabled: Default::default(),
            ghost_element_hover: Default::default(),
            ghost_element_selected: Default::default(),
            hidden: Default::default(),
            hidden_background: Default::default(),
            hidden_border: Default::default(),
            hint: Default::default(),
            hint_background: Default::default(),
            hint_border: Default::default(),
            icon: Default::default(),
            icon_accent: Default::default(),
            icon_disabled: Default::default(),
            icon_muted: Default::default(),
            icon_placeholder: Default::default(),
            ignored: Default::default(),
            ignored_background: Default::default(),
            ignored_border: Default::default(),
            info: Default::default(),
            info_background: Default::default(),
            info_border: Default::default(),
            link_text_hover: Default::default(),
            modified: Default::default(),
            modified_background: Default::default(),
            modified_border: Default::default(),
            pane_focused_border: Default::default(),
            panel_background: Default::default(),
            panel_focused_border: Default::default(),
            players: Default::default(),
            predictive: Default::default(),
            predictive_background: Default::default(),
            predictive_border: Default::default(),
            renamed: Default::default(),
            renamed_background: Default::default(),
            renamed_border: Default::default(),
            scrollbar_thumb_background: Default::default(),
            scrollbar_thumb_border: Default::default(),
            scrollbar_thumb_hover_background: Default::default(),
            scrollbar_track_background: Default::default(),
            scrollbar_track_border: Default::default(),
            search_match_background: Default::default(),
            status_bar_background: Default::default(),
            success: Default::default(),
            success_background: Default::default(),
            success_border: Default::default(),
            surface_background: Default::default(),
            syntax: Default::default(),
            tab_active_background: Default::default(),
            tab_bar_background: Default::default(),
            tab_inactive_background: Default::default(),
            terminal_ansi_black: Default::default(),
            terminal_ansi_blue: Default::default(),
            terminal_ansi_bright_black: Default::default(),
            terminal_ansi_bright_blue: Default::default(),
            terminal_ansi_bright_cyan: Default::default(),
            terminal_ansi_bright_green: Default::default(),
            terminal_ansi_bright_magenta: Default::default(),
            terminal_ansi_bright_red: Default::default(),
            terminal_ansi_bright_white: Default::default(),
            terminal_ansi_bright_yellow: Default::default(),
            terminal_ansi_cyan: Default::default(),
            terminal_ansi_dim_black: Default::default(),
            terminal_ansi_dim_blue: Default::default(),
            terminal_ansi_dim_cyan: Default::default(),
            terminal_ansi_dim_green: Default::default(),
            terminal_ansi_dim_magenta: Default::default(),
            terminal_ansi_dim_red: Default::default(),
            terminal_ansi_dim_white: Default::default(),
            terminal_ansi_dim_yellow: Default::default(),
            terminal_ansi_green: Default::default(),
            terminal_ansi_magenta: Default::default(),
            terminal_ansi_red: Default::default(),
            terminal_ansi_white: Default::default(),
            terminal_ansi_yellow: Default::default(),
            terminal_background: Default::default(),
            terminal_bright_foreground: Default::default(),
            terminal_dim_foreground: Default::default(),
            terminal_foreground: Default::default(),
            text: Default::default(),
            text_accent: Default::default(),
            text_disabled: Default::default(),
            text_muted: Default::default(),
            text_placeholder: Default::default(),
            title_bar_background: Default::default(),
            toolbar_background: Default::default(),
            unreachable: Default::default(),
            unreachable_background: Default::default(),
            unreachable_border: Default::default(),
            warning: Default::default(),
            warning_background: Default::default(),
            warning_border: Default::default(),
        }
    }
}
