pub mod canonicalized_path;
pub mod download;
pub(crate) mod formatter;
pub mod grammar;
pub mod icons;
pub mod language;
pub(crate) mod languages;
pub mod process_command;
pub mod ts_highlight_query;
