default:
    @just build

start:
    npm run start

install:
    npm install

typecheck: install
    npm run typecheck

check:
    tsx validate.ts
    pnpm test

build: typecheck check
    npm run build
