name: release-common
on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: false

jobs:
  build:
    strategy:
      matrix:
        runner:
          - windows-latest
          - windows-11-arm # No -latest tag available
          - macos-latest
          - macos-15-intel # No -latest tag available

        include:
          - runner: windows-latest
            code: windows-x64
            extension: .exe
            archive: zip
          - runner: windows-11-arm
            code: windows-arm64
            extension: .exe
            archive: zip
          - runner: macos-15-intel
            code: macos-x64
            extension:
            archive: tar.gz
          - runner: macos-latest
            code: macos-arm64
            extension:
            archive: tar.gz

    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref }}
      - name: Build
        run: cargo build --profile release-lto --locked

      - name: Package zip
        if: matrix.archive == 'zip'
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Path "ki-${{ matrix.code }}/bin"
          Copy-Item "target/release-lto/ki${{ matrix.extension }}" "ki-${{ matrix.code }}/bin/ki${{ matrix.extension }}"
          Push-Location "ki-${{ matrix.code }}"
          Compress-Archive -Path "bin" -DestinationPath "../ki-${{ matrix.code }}.zip"
          Pop-Location

      - name: Package tarball
        if: matrix.archive == 'tar.gz'
        run: |
          mkdir -p "ki-${{ matrix.code }}/bin"
          cp "target/release-lto/ki" "ki-${{ matrix.code }}/bin/ki"
          chmod 755 "ki-${{ matrix.code }}/bin/ki"
          tar -czf "ki-${{ matrix.code }}.tar.gz" -C "ki-${{ matrix.code }}" bin

      - name: Upload
        uses: actions/upload-artifact@v6
        with:
          name: ki-${{ matrix.code }}
          path: ki-${{ matrix.code }}.${{ matrix.archive }}
          retention-days: 1

  # GitHub doesn't provide musl runners, so we have to work around that
  build-musl:
    strategy:
      matrix:
        runner:
          - ubuntu-latest
          - ubuntu-24.04-arm # No -latest tag available

        include:
          - runner: ubuntu-latest
            code: linux-x64
            rustup_target: x86_64-unknown-linux-musl
          - runner: ubuntu-24.04-arm
            code: linux-arm64
            rustup_target: aarch64-unknown-linux-musl

    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.ref }}
      - name: Get musl
        run: |
          sudo apt install musl-tools
          rustup target add ${{ matrix.rustup_target }}

      - name: Build
        run: cargo build --profile release-lto --locked --target ${{ matrix.rustup_target }}

      - name: Package
        run: |
          mkdir -p "ki-${{ matrix.code }}/bin"
          cp "target/${{ matrix.rustup_target }}/release-lto/ki" "ki-${{ matrix.code }}/bin/ki"
          chmod 755 "ki-${{ matrix.code }}/bin/ki"
          tar -czf "ki-${{ matrix.code }}.tar.gz" -C "ki-${{ matrix.code }}" bin

      - name: Upload
        uses: actions/upload-artifact@v6
        with:
          name: ki-${{ matrix.code }}
          path: ki-${{ matrix.code }}.tar.gz
          retention-days: 1
